# Generated by Django 6.0.2 on 2026-03-06 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("plumbing", "Plumbing"),
                            ("electrical", "Electrical"),
                            ("appliance", "Appliance"),
                            ("structural", "Structural"),
                            ("pest", "Pest Control"),
                            ("hvac", "Heating / AC"),
                            ("security", "Security"),
                            ("cleaning", "Cleaning"),
                            ("noise", "Noise Complaint"),
                            ("damage", "Property Damage"),
                            ("tenant", "Tenant Issue"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("emergency", "Emergency"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "reported_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Who reported this (tenant name, neighbor, etc.)",
                        max_length=255,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contractor or person assigned to fix this",
                        max_length=255,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="properties.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="problems_pr_user_id_a5de4f_idx"
                    ),
                    models.Index(
                        fields=["property", "status"],
                        name="problems_pr_propert_ad405b_idx",
                    ),
                    models.Index(
                        fields=["priority"], name="problems_pr_priorit_de2898_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="problems_pr_created_428612_idx"
                    ),
                ],
            },
        ),
    ]
