# Generated by Django 6.0.2 on 2026-03-06 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="data_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this user sees and manages data belonging to the data_owner user.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delegates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
