# Generated by Django 6.0.2 on 2026-04-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_modules_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allowed_lease_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of lease IDs this user can access. Empty = all leases.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="allowed_property_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of property IDs this user can access. Empty = all properties.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="allowed_tenant_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of tenant IDs this user can access. Empty = all tenants.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="allowed_vehicle_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of vehicle IDs this user can access. Empty = all vehicles.",
            ),
        ),
    ]
