# Generated by Django 6.0.2 on 2026-03-06 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("rent_due", "Rent Due"),
                    ("overdue", "Overdue"),
                    ("lease_expiry", "Lease Expiry"),
                    ("document_expiry", "Document Expiry"),
                    ("payment_received", "Payment Received"),
                    ("info", "Info"),
                ],
                max_length=20,
            ),
        ),
    ]
