# Generated by Django 6.0.2 on 2026-04-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0002_notification_related_property_notification_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("rent_due", "Rent Due"),
                    ("overdue", "Overdue"),
                    ("lease_expiry", "Lease Expiry"),
                    ("document_expiry", "Document Expiry"),
                    ("payment_received", "Payment Received"),
                    ("info", "Info"),
                ],
                max_length=30,
            ),
        ),
    ]
