# Generated by Django 6.0.2 on 2026-04-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("rent_due", "Rent Due"),
                    ("overdue", "Overdue"),
                    ("lease_expiry", "Lease Expiry"),
                    ("document_expiry", "Document Expiry"),
                    ("payment_received", "Payment Received"),
                    ("health", "Health Alert"),
                    ("info", "Info"),
                ],
                max_length=30,
            ),
        ),
    ]
