# Generated by Django 6.0.2 on 2026-04-02 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0002_add_parent_property_and_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        help_text="Registration plate, e.g. CB1234AB", max_length=20
                    ),
                ),
                (
                    "make",
                    models.CharField(
                        help_text="Manufacturer, e.g. Toyota", max_length=100
                    ),
                ),
                (
                    "model",
                    models.CharField(help_text="Model, e.g. Corolla", max_length=100),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Year of manufacture", null=True
                    ),
                ),
                ("color", models.CharField(blank=True, default="", max_length=50)),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("lpg", "LPG"),
                            ("electric", "Electric"),
                            ("hybrid", "Hybrid"),
                            ("plugin_hybrid", "Plug-in Hybrid"),
                            ("cng", "CNG"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Vehicle Identification Number",
                        max_length=17,
                    ),
                ),
                (
                    "engine_cc",
                    models.PositiveIntegerField(
                        blank=True, help_text="Engine displacement in cc", null=True
                    ),
                ),
                ("first_registration_date", models.DateField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False = sold/scrapped, hidden from active views",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_property",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: assign this vehicle to a property",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicles",
                        to="properties.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleObligation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obligation_type",
                    models.CharField(
                        choices=[
                            ("mtpl", "Гражданска застраховка"),
                            ("kasko", "Каско"),
                            ("vignette", "Винетка"),
                            ("mot", "Технически преглед"),
                            ("vehicle_tax", "Данък МПС"),
                            ("green_card", "Зелена карта"),
                            ("assistance", "Асистанс"),
                            ("custom", "Друго"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "custom_type_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Only used when obligation_type="custom"',
                        max_length=100,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="When this obligation starts / was purchased"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="When this obligation expires. Null = no expiry (e.g., one-time registration)",
                        null=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Insurance company, service center, etc.",
                        max_length=200,
                    ),
                ),
                (
                    "policy_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount paid for this obligation",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="BGN", max_length=3)),
                (
                    "reminder_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Days before end_date to trigger reminders, e.g. [30, 7, 1]",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="True = the active/latest obligation of this type for this vehicle",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obligations",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-end_date", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ObligationFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="vehicle_docs/")),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="vehicles.vehicleobligation",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remind_at", models.DateField(help_text="Date to send this reminder")),
                ("sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notification_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="FK to Notification record once sent",
                        null=True,
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="vehicles.vehicleobligation",
                    ),
                ),
            ],
            options={
                "ordering": ["remind_at"],
            },
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["user", "is_active"], name="vehicles_ve_user_id_4053a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["plate_number"], name="vehicles_ve_plate_n_a3accc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleobligation",
            index=models.Index(
                fields=["vehicle", "obligation_type", "is_current"],
                name="vehicles_ve_vehicle_7400dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleobligation",
            index=models.Index(
                fields=["end_date"], name="vehicles_ve_end_dat_6de000_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicleobligation",
            index=models.Index(
                fields=["is_current"], name="vehicles_ve_is_curr_10d4b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclereminder",
            index=models.Index(
                fields=["remind_at", "sent"], name="vehicles_ve_remind__86c45c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vehiclereminder",
            unique_together={("obligation", "remind_at")},
        ),
    ]
