# Generated by Django 6.0.2 on 2026-03-23 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("stock", "Stock"),
                            ("etf", "ETF"),
                            ("crypto", "Crypto"),
                            ("bond", "Bond"),
                            ("fund", "Fund"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sector", models.CharField(blank=True, default="", max_length=100)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=6, default=0, max_digits=14),
                ),
                (
                    "avg_purchase_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=3)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["ticker"],
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=100)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("GBP", "GBP"),
                            ("EUR", "EUR"),
                            ("BGN", "BGN"),
                            ("USD", "USD"),
                            ("CHF", "CHF"),
                        ],
                        default="EUR",
                        max_length=3,
                    ),
                ),
                ("broker", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "condition",
                    models.CharField(
                        choices=[("above", "Above"), ("below", "Below")], max_length=5
                    ),
                ),
                ("target_price", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("triggered", models.BooleanField(default=False)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("buy", "Buy"),
                            ("sell", "Sell"),
                            ("dividend", "Dividend"),
                            ("fee", "Fee"),
                            ("split", "Split"),
                            ("transfer_in", "Transfer In"),
                            ("transfer_out", "Transfer Out"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=6, default=0, max_digits=14),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WatchlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("stock", "Stock"),
                            ("etf", "ETF"),
                            ("crypto", "Crypto"),
                            ("bond", "Bond"),
                            ("fund", "Fund"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["ticker"],
            },
        ),
        migrations.RemoveIndex(
            model_name="investment",
            name="investments__user_id_3b8e4a_idx",
        ),
        migrations.RemoveIndex(
            model_name="investment",
            name="investments__investm_a1c2d3_idx",
        ),
        migrations.RemoveIndex(
            model_name="investment",
            name="investments__investm_d4e5f6_idx",
        ),
        migrations.AddField(
            model_name="holding",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holdings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="holding",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holdings",
                to="investments.portfolio",
            ),
        ),
        migrations.AddField(
            model_name="pricealert",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="holding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="investments.holding",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="watchlistitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="investment",
            name="property",
        ),
        migrations.RemoveField(
            model_name="investment",
            name="user",
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(fields=["user"], name="investments_user_id_d35513_idx"),
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(
                fields=["currency"], name="investments_currenc_53fce7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holding",
            index=models.Index(
                fields=["user", "portfolio"], name="investments_user_id_f3218c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="holding",
            index=models.Index(fields=["ticker"], name="investments_ticker_fa3aaa_idx"),
        ),
        migrations.AddIndex(
            model_name="holding",
            index=models.Index(
                fields=["asset_type"], name="investments_asset_t_562d2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "holding"], name="investments_user_id_103df3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type"], name="investments_transac_554469_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["-date"], name="investments_date_812f76_idx"),
        ),
        migrations.DeleteModel(
            name="Investment",
        ),
    ]
