# Generated by Django 6.0.2 on 2026-04-01 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0002_holding_portfolio_pricealert_transaction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Label for this analysis", max_length=255
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("area", models.CharField(blank=True, default="", max_length=200)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("studio", "Studio"),
                            ("penthouse", "Penthouse"),
                            ("commercial", "Commercial"),
                            ("villa", "Villa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("square_meters", models.DecimalField(decimal_places=2, max_digits=10)),
                ("asking_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("parking_included", models.BooleanField(default=False)),
                (
                    "parking_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Separate parking cost if not included",
                        max_digits=10,
                    ),
                ),
                ("num_bedrooms", models.IntegerField(default=1)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New Build"),
                            ("renovated", "Renovated"),
                            ("good", "Good Condition"),
                            ("needs_work", "Needs Work"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                (
                    "furnishing",
                    models.CharField(
                        choices=[
                            ("unfurnished", "Unfurnished"),
                            ("semi", "Semi-Furnished"),
                            ("fully", "Fully Furnished"),
                        ],
                        default="unfurnished",
                        max_length=20,
                    ),
                ),
                ("floor", models.IntegerField(blank=True, null=True)),
                ("total_floors", models.IntegerField(blank=True, null=True)),
                ("year_built", models.IntegerField(blank=True, null=True)),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="asking_price + parking_price",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "price_per_sqm",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "market_avg_sqm",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "price_vs_market_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive = above market, negative = below",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "estimated_monthly_rent",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "estimated_annual_rent",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "gross_rental_yield",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "net_rental_yield",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "estimated_airbnb_monthly",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "airbnb_annual_revenue",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "airbnb_yield",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "cap_rate",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "roi_5_year",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "roi_10_year",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("break_even_months", models.IntegerField(blank=True, null=True)),
                (
                    "area_heat_score",
                    models.IntegerField(
                        blank=True,
                        help_text="0-100 neighborhood desirability",
                        null=True,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("strong_buy", "Strong Buy"),
                            ("buy", "Buy"),
                            ("hold", "Hold"),
                            ("overpriced", "Overpriced"),
                            ("avoid", "Avoid"),
                        ],
                        default="hold",
                        max_length=20,
                    ),
                ),
                (
                    "verdict_score",
                    models.IntegerField(
                        default=0, help_text="0-100 overall investment score"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Property analyses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="investments_user_id_b3ee3f_idx",
                    ),
                    models.Index(
                        fields=["country", "city"],
                        name="investments_country_f90fe0_idx",
                    ),
                    models.Index(
                        fields=["verdict"], name="investments_verdict_c9ff66_idx"
                    ),
                ],
            },
        ),
    ]
