# Generated by Django 6.0.2 on 2026-04-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0003_propertyanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyanalysis",
            name="has_ac",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="has_balcony",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="has_elevator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="has_garden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="has_heating",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="has_patio",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="has_storage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="num_bathrooms",
            field=models.IntegerField(default=1),
        ),
    ]
