# Generated by Django 6.0.2 on 2026-04-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "investments",
            "0004_propertyanalysis_has_ac_propertyanalysis_has_balcony_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyanalysis",
            name="has_gym",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="has_pool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="has_view",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="monthly_fees",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monthly condo/maintenance fees",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="renovation_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Estimated renovation cost in EUR",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="view_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="none/city/sea/mountain/garden",
                max_length=20,
            ),
        ),
    ]
