# Generated by Django 6.0.2 on 2026-04-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "investments",
            "0005_propertyanalysis_has_gym_propertyanalysis_has_pool_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyanalysis",
            name="construction_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="panel/brick/reinforced/wood/unknown",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="location_score",
            field=models.IntegerField(
                blank=True, help_text="0-15 location quality score", null=True
            ),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="market_trend_score",
            field=models.IntegerField(
                blank=True, help_text="0-10 market trend score", null=True
            ),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="near_hospital",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="near_metro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="near_park",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="near_school",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="noise_level",
            field=models.CharField(
                blank=True, default="", help_text="quiet/moderate/noisy", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="recommendation_text",
            field=models.TextField(
                blank=True, default="", help_text="Detailed recommendation text"
            ),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="recommendation_text_bg",
            field=models.TextField(
                blank=True, default="", help_text="Recommendation in Bulgarian"
            ),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="renovation_roi",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Renovation ROI %",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="risk_factors",
            field=models.JSONField(
                blank=True, default=list, help_text="List of risk factor dicts"
            ),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="risk_score",
            field=models.IntegerField(
                blank=True, help_text="0-10 risk score (higher=better)", null=True
            ),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="score_breakdown_json",
            field=models.JSONField(
                blank=True, default=dict, help_text="Full 8-dimension score breakdown"
            ),
        ),
    ]
