# Generated by Django 6.0.2 on 2026-04-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0006_propertyanalysis_construction_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyanalysis",
            name="garden_sqm",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Garden area in sqm",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="parking_sqm",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Parking space area in sqm",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="patio_sqm",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Patio/veranda area in sqm",
                max_digits=8,
            ),
        ),
    ]
