# Generated by Django 6.0.2 on 2026-04-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0007_add_garden_patio_parking_sqm"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyanalysis",
            name="exposure",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Compass orientation: south/southeast/east/southwest/west/northwest/north/northeast",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="propertyanalysis",
            name="layout_description",
            field=models.TextField(
                blank=True, default="", help_text="Room layout description"
            ),
        ),
    ]
