# Generated by Django 6.0.2 on 2026-02-27 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "id_number",
                    models.CharField(
                        blank=True,
                        help_text="National ID or passport",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                ("bank_iban", models.CharField(blank=True, max_length=50, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The manager who manages this owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Friendly name, e.g. "Sofia Central Apt"',
                        max_length=255,
                    ),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(default="Bulgaria", max_length=100)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("studio", "Studio"),
                            ("commercial", "Commercial"),
                        ],
                        default="apartment",
                        max_length=20,
                    ),
                ),
                (
                    "cadastral_number",
                    models.CharField(
                        blank=True,
                        help_text="Кадастрален номер",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "square_meters",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "mortgage_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mortgage_account_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mortgage_monthly_payment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "electricity_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "electricity_account_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "water_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "water_account_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gas_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gas_account_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "heating_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "heating_account_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "internet_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "internet_account_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "insurance_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "insurance_policy_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "annual_insurance_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "building_management_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "building_management_account_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "building_management_monthly_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "security_provider",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "security_account_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "front_door_code",
                    models.CharField(
                        blank=True,
                        help_text="Front door access code",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "lock_box_code",
                    models.CharField(
                        blank=True,
                        help_text="Lock box access code",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The manager",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The property owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="properties.propertyowner",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_number", models.CharField(max_length=20)),
                ("floor", models.IntegerField(blank=True, null=True)),
                (
                    "square_meters",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="properties.property",
                    ),
                ),
            ],
        ),
    ]
