# Generated by Django 6.0.2 on 2026-03-07 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="parent_property",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent property this is linked to (e.g. apartment for a parking spot)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_properties",
                to="properties.property",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("house", "House"),
                    ("studio", "Studio"),
                    ("commercial", "Commercial"),
                    ("parking", "Parking"),
                    ("garage", "Garage"),
                    ("storage", "Storage"),
                ],
                default="apartment",
                max_length=20,
            ),
        ),
    ]
