# Generated by Django 6.0.2 on 2026-04-06 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_add_parent_property_and_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("bg_property_tax", "Данък недвижими имоти"),
                            ("bg_waste_tax", "Такса битови отпадъци"),
                            ("uk_council_tax", "Council Tax"),
                            ("uk_stamp_duty", "Stamp Duty Land Tax"),
                            ("uk_capital_gains", "Capital Gains Tax"),
                            ("uk_income_tax", "Income Tax (rental)"),
                            ("uae_municipality_fee", "Municipality Fee"),
                            ("uae_housing_fee", "Housing Fee (DEWA)"),
                            ("uae_service_charge", "Service Charge"),
                            ("custom", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "custom_tax_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Only used when tax_type="custom"',
                        max_length=100,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tax amount per period",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("one_time", "One-time"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("biannual", "Biannual"),
                            ("annual", "Annual"),
                        ],
                        default="annual",
                        max_length=20,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Next due date for this tax payment",
                        null=True,
                    ),
                ),
                (
                    "paid_until",
                    models.DateField(
                        blank=True, help_text="Tax is paid up to this date", null=True
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tax authority / municipality / council name",
                        max_length=200,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tax reference / account number",
                        max_length=100,
                    ),
                ),
                (
                    "helper_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Explanatory text about this tax type",
                    ),
                ),
                (
                    "reminder_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Days before due_date to trigger reminders, e.g. [30, 7, 1]",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="True = the active/latest tax entry of this type for this property",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        default=False, help_text="Whether the current period is paid"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxes",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Property taxes",
                "ordering": ["tax_type", "-due_date"],
            },
        ),
        migrations.CreateModel(
            name="TaxReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remind_at", models.DateField(help_text="Date to send this reminder")),
                ("sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("notification_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "tax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="properties.propertytax",
                    ),
                ),
            ],
            options={
                "ordering": ["remind_at"],
            },
        ),
        migrations.AddIndex(
            model_name="propertytax",
            index=models.Index(
                fields=["property", "tax_type", "is_current"],
                name="properties__propert_879537_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propertytax",
            index=models.Index(
                fields=["due_date"], name="properties__due_dat_307464_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taxreminder",
            index=models.Index(
                fields=["remind_at", "sent"], name="properties__remind__4d43fe_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taxreminder",
            unique_together={("tax", "remind_at")},
        ),
    ]
