# Generated by Django 6.0.2 on 2026-04-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_propertytax_taxreminder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="notary_act_date",
            field=models.DateField(
                blank=True, help_text="Дата на нотариален акт", null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="notary_act_number",
            field=models.CharField(
                blank=True,
                help_text="Нотариален акт №, том, рег., дело",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_registry_number",
            field=models.CharField(
                blank=True, help_text="Имотна партида №", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="seller_name",
            field=models.CharField(
                blank=True, help_text="Продавач", max_length=255, null=True
            ),
        ),
    ]
