# Generated by Django 6.0.2 on 2026-02-27 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("leases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentpayment",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rent_payments",
                to="leases.lease",
            ),
        ),
    ]
