# ── seed_biomarkers.py ────────────────────────────────────────────────
# Management command: python manage.py seed_biomarkers
# Seeds BiomarkerCategory + Biomarker tables with ~40 common blood test markers.
# Idempotent — uses update_or_create keyed on slug/abbreviation.
#
# §NAV: This is reference data. After seeding, parsers.py matches PDF text → these rows.
# §I18N: Each marker has EN + BG names, descriptions, and lifestyle tips.

from django.core.management.base import BaseCommand
from health.models import BiomarkerCategory, Biomarker


# ── Categories ───────────────────────────────────────────────────────

CATEGORIES = [
    {
        'slug': 'cbc', 'name': 'Complete Blood Count', 'name_bg': 'Пълна кръвна картина',
        'icon': '🩸', 'body_system': 'blood', 'sort_order': 1,
    },
    {
        'slug': 'lipid_panel', 'name': 'Lipid Panel', 'name_bg': 'Липиден профил',
        'icon': '❤️', 'body_system': 'heart', 'sort_order': 2,
    },
    {
        'slug': 'metabolic', 'name': 'Metabolic Panel', 'name_bg': 'Метаболитен панел',
        'icon': '⚡', 'body_system': 'metabolic', 'sort_order': 3,
    },
    {
        'slug': 'liver', 'name': 'Liver Function', 'name_bg': 'Чернодробна функция',
        'icon': '🫁', 'body_system': 'liver', 'sort_order': 4,
    },
    {
        'slug': 'kidney', 'name': 'Kidney Function', 'name_bg': 'Бъбречна функция',
        'icon': '🫘', 'body_system': 'kidney', 'sort_order': 5,
    },
    {
        'slug': 'thyroid', 'name': 'Thyroid', 'name_bg': 'Щитовидна жлеза',
        'icon': '🦋', 'body_system': 'thyroid', 'sort_order': 6,
    },
    {
        'slug': 'vitamins', 'name': 'Vitamins & Minerals', 'name_bg': 'Витамини и минерали',
        'icon': '💊', 'body_system': 'nutrition', 'sort_order': 7,
    },
    {
        'slug': 'iron_studies', 'name': 'Iron Studies', 'name_bg': 'Желязо',
        'icon': '🔩', 'body_system': 'blood', 'sort_order': 8,
    },
    {
        'slug': 'inflammation', 'name': 'Inflammation', 'name_bg': 'Възпалителни маркери',
        'icon': '🔥', 'body_system': 'immune', 'sort_order': 9,
    },
    {
        'slug': 'hormones', 'name': 'Hormones', 'name_bg': 'Хормони',
        'icon': '⚖️', 'body_system': 'hormonal', 'sort_order': 10,
    },
    {
        'slug': 'electrolytes', 'name': 'Electrolytes', 'name_bg': 'Електролити',
        'icon': '⚡', 'body_system': 'metabolic', 'sort_order': 11,
    },
    {
        'slug': 'proteins', 'name': 'Protein Panel', 'name_bg': 'Протеинов панел',
        'icon': '🧬', 'body_system': 'liver', 'sort_order': 12,
    },
    {
        'slug': 'tumor_markers', 'name': 'Tumor Markers', 'name_bg': 'Туморни маркери',
        'icon': '🔬', 'body_system': 'immune', 'sort_order': 13,
    },
]


# ── Biomarkers ───────────────────────────────────────────────────────
# Each entry: category_slug, abbreviation (unique key), name, name_bg,
# unit, aliases (for PDF matching), reference ranges (M/F), optimal range,
# critical thresholds, descriptions, meanings, tips.
#
# §RANGE: ref_min/max = normal range. optimal = ideal functional range.
#         critical = needs immediate medical attention.
# §ALIAS: aliases include BG names, abbreviations, lab-specific spellings.

BIOMARKERS = [
    # ── CBC ──────────────────────────────────────────────────────────
    {
        'category': 'cbc', 'abbreviation': 'HGB', 'name': 'Hemoglobin', 'name_bg': 'Хемоглобин',
        'unit': 'g/L', 'alt_units': [{'unit': 'g/dL', 'factor': 0.1}],
        'aliases': ['Hb', 'HGB', 'Hemoglobin', 'Хемоглобин', 'Haemoglobin'],
        'ref_min_male': 130, 'ref_max_male': 175, 'ref_min_female': 120, 'ref_max_female': 160,
        'optimal_min': 140, 'optimal_max': 165, 'critical_low': 70, 'critical_high': 200,
        'description': 'Protein in red blood cells that carries oxygen throughout your body. Essential for energy and organ function.',
        'description_bg': 'Протеин в червените кръвни клетки, който пренася кислород в тялото. Важен за енергията и функцията на органите.',
        'high_meaning': 'May indicate dehydration, lung disease, or polycythemia. Living at high altitude can also raise levels.',
        'high_meaning_bg': 'Може да означава дехидратация, белодробно заболяване или полицитемия.',
        'low_meaning': 'Suggests anemia — possibly from iron deficiency, B12 deficiency, or chronic disease. Causes fatigue and weakness.',
        'low_meaning_bg': 'Предполага анемия — евентуално от дефицит на желязо, B12 или хронично заболяване. Причинява умора и слабост.',
        'improve_tips': ['Eat iron-rich foods: red meat, spinach, lentils', 'Pair iron foods with vitamin C for better absorption', 'Check for B12 and folate deficiency', 'Stay hydrated'],
        'improve_tips_bg': ['Яжте храни богати на желязо: червено месо, спанак, леща', 'Комбинирайте с витамин С за по-добра абсорбция', 'Проверете за дефицит на B12 и фолиева киселина', 'Пийте достатъчно вода'],
        'sort_order': 1,
    },
    {
        'category': 'cbc', 'abbreviation': 'WBC', 'name': 'White Blood Cells', 'name_bg': 'Левкоцити',
        'unit': '×10⁹/L', 'alt_units': [{'unit': 'cells/μL', 'factor': 1000}],
        'aliases': ['WBC', 'Leukocytes', 'Левкоцити', 'White blood cells', 'LEU'],
        'ref_min_male': 4.0, 'ref_max_male': 11.0, 'ref_min_female': 4.0, 'ref_max_female': 11.0,
        'optimal_min': 5.0, 'optimal_max': 8.0, 'critical_low': 2.0, 'critical_high': 30.0,
        'description': 'Immune system cells that fight infection. Count indicates immune activity level.',
        'description_bg': 'Клетки на имунната система, които се борят с инфекции. Броят показва нивото на имунна активност.',
        'high_meaning': 'Active infection, inflammation, stress, or rarely leukemia. Smoking also raises WBC.',
        'high_meaning_bg': 'Активна инфекция, възпаление, стрес или рядко левкемия. Тютюнопушенето също повишава левкоцитите.',
        'low_meaning': 'Weakened immune system — could be viral infection, autoimmune, or bone marrow issue.',
        'low_meaning_bg': 'Отслабена имунна система — може да е вирусна инфекция, автоимунно или проблем с костния мозък.',
        'improve_tips': ['Get adequate sleep (7-9 hours)', 'Manage stress — cortisol suppresses immunity', 'Exercise moderately', 'Eat zinc-rich foods: pumpkin seeds, chickpeas'],
        'improve_tips_bg': ['Спете достатъчно (7-9 часа)', 'Управлявайте стреса — кортизолът потиска имунитета', 'Умерени физически упражнения', 'Яжте храни богати на цинк: тиквени семки, нахут'],
        'sort_order': 2,
    },
    {
        'category': 'cbc', 'abbreviation': 'RBC', 'name': 'Red Blood Cells', 'name_bg': 'Еритроцити',
        'unit': '×10¹²/L', 'alt_units': [{'unit': 'M/μL', 'factor': 1}],
        'aliases': ['RBC', 'Erythrocytes', 'Еритроцити', 'Red blood cells', 'ERY'],
        'ref_min_male': 4.5, 'ref_max_male': 5.5, 'ref_min_female': 3.8, 'ref_max_female': 5.1,
        'optimal_min': 4.5, 'optimal_max': 5.2, 'critical_low': 2.5, 'critical_high': 7.0,
        'description': 'Cells that carry oxygen from lungs to tissues. Count reflects oxygen-carrying capacity.',
        'description_bg': 'Клетки, които пренасят кислород от белите дробове до тъканите.',
        'high_meaning': 'Dehydration, lung disease, or polycythemia vera. May increase blood clot risk.',
        'high_meaning_bg': 'Дехидратация, белодробно заболяване или полицитемия вера.',
        'low_meaning': 'Anemia — blood loss, nutritional deficiency, or chronic disease.',
        'low_meaning_bg': 'Анемия — кръвозагуба, хранителен дефицит или хронично заболяване.',
        'improve_tips': ['Address underlying anemia cause', 'Iron + B12 + folate supplementation if deficient', 'Regular exercise improves RBC production'],
        'improve_tips_bg': ['Адресирайте основната причина за анемията', 'Добавки на желязо + B12 + фолиева киселина при дефицит', 'Редовните упражнения подобряват производството на еритроцити'],
        'sort_order': 3,
    },
    {
        'category': 'cbc', 'abbreviation': 'PLT', 'name': 'Platelets', 'name_bg': 'Тромбоцити',
        'unit': '×10⁹/L', 'alt_units': [{'unit': 'K/μL', 'factor': 1}],
        'aliases': ['PLT', 'Platelets', 'Тромбоцити', 'Thrombocytes', 'THR'],
        'ref_min_male': 150, 'ref_max_male': 400, 'ref_min_female': 150, 'ref_max_female': 400,
        'optimal_min': 200, 'optimal_max': 350, 'critical_low': 50, 'critical_high': 1000,
        'description': 'Blood cells that help clotting. Essential for wound healing and preventing excessive bleeding.',
        'description_bg': 'Кръвни клетки, които помагат за съсирването. Важни за зарастването на рани.',
        'high_meaning': 'Inflammation, infection, iron deficiency, or rarely myeloproliferative disorder.',
        'high_meaning_bg': 'Възпаление, инфекция, дефицит на желязо или рядко миелопролиферативно разстройство.',
        'low_meaning': 'Increased bleeding risk. Could be viral infection, autoimmune, or medication effect.',
        'low_meaning_bg': 'Повишен риск от кървене. Може да е вирусна инфекция, автоимунно или ефект на лекарства.',
        'improve_tips': ['Avoid alcohol (suppresses platelet production)', 'Eat folate-rich foods', 'Review medications with doctor if low'],
        'improve_tips_bg': ['Избягвайте алкохол (потиска производството на тромбоцити)', 'Яжте храни богати на фолат', 'Консултирайте се с лекар при ниски стойности'],
        'sort_order': 4,
    },
    {
        'category': 'cbc', 'abbreviation': 'HCT', 'name': 'Hematocrit', 'name_bg': 'Хематокрит',
        'unit': '%', 'alt_units': [{'unit': 'L/L', 'factor': 0.01}],
        'aliases': ['HCT', 'Hematocrit', 'Хематокрит', 'Ht', 'PCV'],
        'ref_min_male': 40, 'ref_max_male': 54, 'ref_min_female': 36, 'ref_max_female': 48,
        'optimal_min': 42, 'optimal_max': 50, 'critical_low': 25, 'critical_high': 65,
        'description': 'Percentage of blood volume occupied by red blood cells. Reflects hydration and oxygen capacity.',
        'description_bg': 'Процент от обема на кръвта, зает от червени кръвни клетки. Отразява хидратацията и кислородния капацитет.',
        'high_meaning': 'Dehydration is the most common cause. Also polycythemia or chronic lung disease.',
        'high_meaning_bg': 'Дехидратацията е най-честата причина. Също полицитемия или хронично белодробно заболяване.',
        'low_meaning': 'Anemia, blood loss, or overhydration.',
        'low_meaning_bg': 'Анемия, кръвозагуба или свръххидратация.',
        'improve_tips': ['Stay well hydrated', 'Address iron deficiency if present', 'Moderate altitude training can help'],
        'improve_tips_bg': ['Пийте достатъчно вода', 'Адресирайте дефицита на желязо ако е налице', 'Умерени тренировки на височина могат да помогнат'],
        'sort_order': 5,
    },

    {
        'category': 'cbc', 'abbreviation': 'MCV', 'name': 'Mean Corpuscular Volume', 'name_bg': 'Среден обем на еритроцитите',
        'unit': 'fL', 'alt_units': [],
        'aliases': ['MCV', 'Mean corpuscular volume', 'Ср. обем на еритроцитите', 'Mean Cell Volume'],
        'ref_min_male': 82, 'ref_max_male': 98, 'ref_min_female': 82, 'ref_max_female': 98,
        'optimal_min': 84, 'optimal_max': 94, 'critical_low': 60, 'critical_high': 110,
        'description': 'Average size of your red blood cells. Helps classify the type of anemia — small (microcytic), normal, or large (macrocytic) red blood cells.',
        'description_bg': 'Среден размер на червените кръвни клетки. Помага за класифициране на вида анемия — малки (микроцитарни), нормални или големи (макроцитарни) еритроцити.',
        'high_meaning': 'Macrocytic anemia — often from B12 or folate deficiency, alcoholism, liver disease, or hypothyroidism. Red blood cells are too large.',
        'high_meaning_bg': 'Макроцитарна анемия — често от дефицит на B12 или фолат, алкохолизъм, чернодробно заболяване или хипотиреоидизъм. Червените кръвни клетки са прекалено големи.',
        'low_meaning': 'Microcytic anemia — most commonly iron deficiency or thalassemia trait. Red blood cells are too small to carry enough oxygen.',
        'low_meaning_bg': 'Микроцитарна анемия — най-често дефицит на желязо или таласемия. Червените кръвни клетки са прекалено малки за да пренасят достатъчно кислород.',
        'improve_tips': ['Low MCV: check iron, ferritin — iron deficiency is #1 cause', 'High MCV: check B12 and folate levels', 'Reduce alcohol — even moderate drinking raises MCV', 'Thyroid issues can affect MCV — check TSH'],
        'improve_tips_bg': ['Нисък MCV: проверете желязо, феритин — дефицитът на желязо е №1 причина', 'Висок MCV: проверете B12 и фолат', 'Намалете алкохола — дори умерено пиене повишава MCV', 'Тиреоидни проблеми могат да повлияят MCV — проверете ТСХ'],
        'sort_order': 6,
    },
    {
        'category': 'cbc', 'abbreviation': 'MCH', 'name': 'Mean Corpuscular Hemoglobin', 'name_bg': 'Средно съдържание на Hgb в еритроцит',
        'unit': 'pg', 'alt_units': [],
        'aliases': ['MCH', 'Mean corpuscular hemoglobin', 'Ср. Hgb. съдърж. в ер.', 'Ср.Hgb съдърж. в еритр.'],
        'ref_min_male': 27, 'ref_max_male': 33, 'ref_min_female': 27, 'ref_max_female': 33,
        'optimal_min': 28, 'optimal_max': 32, 'critical_low': 20, 'critical_high': 40,
        'description': 'Average amount of hemoglobin inside each red blood cell. Reflects how much oxygen each cell can carry. Closely related to MCV.',
        'description_bg': 'Средно количество хемоглобин в червена кръвна клетка. Отразява колко кислород може да пренася всяка клетка. Тясно свързан с MCV.',
        'high_meaning': 'Same causes as high MCV — B12/folate deficiency, macrocytic anemia.',
        'high_meaning_bg': 'Същите причини като висок MCV — дефицит на B12/фолат, макроцитарна анемия.',
        'low_meaning': 'Iron deficiency or thalassemia — cells are pale and carry less oxygen (hypochromic).',
        'low_meaning_bg': 'Дефицит на желязо или таласемия — клетките са бледи и пренасят по-малко кислород (хипохромни).',
        'improve_tips': ['Follows MCV — address iron or B12/folate deficiency', 'Check ferritin for iron stores', 'Mediterranean diet supports healthy red blood cell production'],
        'improve_tips_bg': ['Следва MCV — адресирайте дефицит на желязо или B12/фолат', 'Проверете феритин за запасите от желязо', 'Средиземноморската диета подпомага здравото производство на еритроцити'],
        'sort_order': 7,
    },
    {
        'category': 'cbc', 'abbreviation': 'MCHC', 'name': 'Mean Corpuscular Hgb Concentration', 'name_bg': 'Средна концентрация на Hgb в еритроцит',
        'unit': 'g/L', 'alt_units': [{'unit': 'g/dL', 'factor': 0.1}],
        'aliases': ['MCHC', 'Mean corpuscular hemoglobin concentration', 'Ср. конц. на Hgb. в еритр.', 'ср.конц.на Нgb в еритр'],
        'ref_min_male': 300, 'ref_max_male': 360, 'ref_min_female': 300, 'ref_max_female': 360,
        'optimal_min': 320, 'optimal_max': 350, 'critical_low': 280, 'critical_high': 380,
        'description': 'Average concentration of hemoglobin in red blood cells. Indicates how "packed" with hemoglobin each cell is. Helps distinguish types of anemia.',
        'description_bg': 'Средна концентрация на хемоглобин в червените кръвни клетки. Показва колко "натоварена" с хемоглобин е всяка клетка.',
        'high_meaning': 'Spherocytosis (hereditary) or severe dehydration. Cells are overly concentrated.',
        'high_meaning_bg': 'Сфероцитоза (наследствена) или тежка дехидратация. Клетките са свръхконцентрирани.',
        'low_meaning': 'Iron deficiency anemia — cells are pale (hypochromic). Also thalassemia.',
        'low_meaning_bg': 'Желязодефицитна анемия — клетките са бледи (хипохромни). Също таласемия.',
        'improve_tips': ['Low MCHC usually means iron deficiency — same tips as for low MCH', 'Stay hydrated if high', 'Check iron panel: serum iron + ferritin + TIBC'],
        'improve_tips_bg': ['Нисък MCHC обикновено означава дефицит на желязо', 'Пийте достатъчно вода при висок', 'Проверете железен панел: серумно желязо + феритин + TIBC'],
        'sort_order': 8,
    },
    {
        'category': 'cbc', 'abbreviation': 'RDW', 'name': 'Red Cell Distribution Width', 'name_bg': 'Девиация на еритроцитно разпределение',
        'unit': '%', 'alt_units': [],
        'aliases': ['RDW', 'RDW%', 'Red cell distribution width', 'Девиация на ер. разпред.', 'Девиация на еритр. р-ие'],
        'ref_min_male': 11.5, 'ref_max_male': 14.5, 'ref_min_female': 11.5, 'ref_max_female': 14.5,
        'optimal_min': 12, 'optimal_max': 14, 'critical_low': None, 'critical_high': 20,
        'description': 'Measures variation in red blood cell size. High RDW means cells are different sizes — a clue to nutritional deficiency or ongoing blood issues.',
        'description_bg': 'Измерва вариацията в размера на червените кръвни клетки. Висок RDW означава, че клетките са с различни размери — индикатор за хранителен дефицит.',
        'high_meaning': 'Mixed population of red blood cells — common in iron, B12, or folate deficiency. Also seen in chronic liver disease. Independently predicts cardiovascular risk.',
        'high_meaning_bg': 'Смесена популация от червени кръвни клетки — често при дефицит на желязо, B12 или фолат. Независим предиктор на сърдечно-съдов риск.',
        'low_meaning': 'Normal — cells are uniform in size. Not clinically significant.',
        'low_meaning_bg': 'Нормално — клетките са с еднакъв размер. Няма клинично значение.',
        'improve_tips': ['Address underlying deficiency (iron, B12, folate)', 'RDW > 14.5% with normal MCV may indicate early iron depletion', 'Elevated RDW is an independent mortality predictor — worth investigating'],
        'improve_tips_bg': ['Адресирайте основния дефицит (желязо, B12, фолат)', 'RDW > 14.5% с нормален MCV може да означава ранно изчерпване на желязото'],
        'sort_order': 9,
    },
    {
        'category': 'cbc', 'abbreviation': 'MPV', 'name': 'Mean Platelet Volume', 'name_bg': 'Среден обем на тромбоцита',
        'unit': 'fL', 'alt_units': [],
        'aliases': ['MPV', 'Mean platelet volume', 'Ср. обем на тромбоцитите', 'ср.обем на тромбоцита'],
        'ref_min_male': 6.5, 'ref_max_male': 12, 'ref_min_female': 6.5, 'ref_max_female': 12,
        'optimal_min': 7.5, 'optimal_max': 11, 'critical_low': None, 'critical_high': None,
        'description': 'Average size of platelets. Larger platelets are younger and more active. Reflects bone marrow platelet production rate.',
        'description_bg': 'Среден размер на тромбоцитите. По-големите тромбоцити са по-млади и по-активни. Отразява скоростта на производство на тромбоцити от костния мозък.',
        'high_meaning': 'Increased platelet production — body is compensating for destruction or loss. Seen with inflammation, diabetes, and cardiovascular risk.',
        'high_meaning_bg': 'Повишено производство на тромбоцити — тялото компенсира за разрушаване или загуба. Свързано с възпаление, диабет и сърдечно-съдов риск.',
        'low_meaning': 'Bone marrow underproduction or older platelets predominating.',
        'low_meaning_bg': 'Недостатъчно производство от костния мозък или преобладаване на стари тромбоцити.',
        'improve_tips': ['MPV is a research marker — no direct lifestyle interventions', 'High MPV with high platelets: discuss aspirin therapy with doctor', 'Address underlying inflammation if MPV is elevated'],
        'improve_tips_bg': ['MPV е изследователски маркер — няма преки лайфстайл интервенции', 'Висок MPV с високи тромбоцити: обсъдете аспиринова терапия с лекар'],
        'sort_order': 10,
    },
    {
        'category': 'cbc', 'abbreviation': 'PCT', 'name': 'Plateletcrit', 'name_bg': 'Тромбокрит',
        'unit': '%', 'alt_units': [],
        'aliases': ['PCT', 'Plateletcrit', 'Тромбокрит'],
        'ref_min_male': 0.17, 'ref_max_male': 0.35, 'ref_min_female': 0.17, 'ref_max_female': 0.35,
        'optimal_min': 0.20, 'optimal_max': 0.32, 'critical_low': None, 'critical_high': None,
        'description': 'Volume fraction of platelets in whole blood (PLT × MPV). Derived metric — useful together with PLT and MPV to interpret platelet status.',
        'description_bg': 'Обемна част на тромбоцитите в цяла кръв (PLT × MPV). Производен показател — полезен заедно с PLT и MPV за оценка на тромбоцитния статус.',
        'high_meaning': 'Elevated total platelet mass — often tracks high platelet count or large platelets. Consider inflammation, reactive thrombocytosis, or cardiovascular risk context.',
        'high_meaning_bg': 'Повишена обща тромбоцитна маса — обикновено съответства на висок брой тромбоцити или по-големи тромбоцити. Възпаление, реактивна тромбоцитоза или сърдечно-съдов риск.',
        'low_meaning': 'Reduced platelet mass — usually mirrors low platelet count; increased bleeding risk.',
        'low_meaning_bg': 'Понижена тромбоцитна маса — обикновено отразява нисък брой тромбоцити; повишен риск от кървене.',
        'improve_tips': ['Interpret alongside PLT and MPV', 'No direct lifestyle action — address the underlying PLT/MPV cause'],
        'improve_tips_bg': ['Тълкувайте заедно с PLT и MPV', 'Няма директна лайфстайл мярка — работете по причината в PLT/MPV'],
        'sort_order': 11,
    },
    {
        'category': 'cbc', 'abbreviation': 'LYM', 'name': 'Lymphocytes (count)', 'name_bg': 'Лимфоцити (бр.)',
        'unit': '×10⁹/L', 'alt_units': [{'unit': 'G/L', 'factor': 1}],
        'aliases': ['LYM', 'Lymphocytes', 'Лимфоцити', 'Лимфоцити-бр.', 'Лимфоцити -бр.', 'LYMF'],
        'ref_min_male': 1.0, 'ref_max_male': 4.8, 'ref_min_female': 1.0, 'ref_max_female': 4.8,
        'optimal_min': 1.5, 'optimal_max': 3.5, 'critical_low': 0.5, 'critical_high': 10,
        'description': 'Key immune cells that fight viruses and produce antibodies. Include T-cells (kill infected cells) and B-cells (make antibodies). Your adaptive immune army.',
        'description_bg': 'Ключови имунни клетки, които се борят с вируси и произвеждат антитела. Включват Т-клетки и B-клетки. Вашата адаптивна имунна армия.',
        'high_meaning': 'Active viral infection (most common), chronic infection, autoimmune disease, or rarely lymphoma. The body is mounting an immune response.',
        'high_meaning_bg': 'Активна вирусна инфекция (най-честа причина), хронична инфекция, автоимунно заболяване или рядко лимфом.',
        'low_meaning': 'Weakened immunity — HIV, immunosuppressive drugs, severe stress, or autoimmune disease. Increased infection risk.',
        'low_meaning_bg': 'Отслабен имунитет — ХИВ, имуносупресивни лекарства, тежък стрес или автоимунно заболяване.',
        'improve_tips': ['Adequate sleep (7-9h) is critical for lymphocyte function', 'Regular moderate exercise boosts lymphocytes', 'Chronic stress and cortisol suppress lymphocytes', 'Zinc, vitamin C, and vitamin D support immune function'],
        'improve_tips_bg': ['Адекватен сън (7-9ч) е критичен за функцията на лимфоцитите', 'Редовни умерени упражнения повишават лимфоцитите', 'Хроничният стрес и кортизолът потискат лимфоцитите', 'Цинк, витамин С и витамин D подпомагат имунната функция'],
        'sort_order': 11,
    },
    {
        'category': 'cbc', 'abbreviation': 'MONO', 'name': 'Monocytes (count)', 'name_bg': 'Моноцити (бр.)',
        'unit': '×10⁹/L', 'alt_units': [{'unit': 'G/L', 'factor': 1}],
        'aliases': ['MONO', 'Monocytes', 'Моноцити', 'Моноцити-бр.', 'Mоноцити-бр.'],
        'ref_min_male': 0.2, 'ref_max_male': 0.8, 'ref_min_female': 0.2, 'ref_max_female': 0.8,
        'optimal_min': 0.3, 'optimal_max': 0.7, 'critical_low': None, 'critical_high': 3.0,
        'description': 'Immune cells that become macrophages — the "cleanup crew" that engulfs pathogens and dead cells. First responders to chronic infections.',
        'description_bg': 'Имунни клетки, които стават макрофаги — "екипът за почистване", който поглъща патогени и мъртви клетки.',
        'high_meaning': 'Chronic infection, inflammation, autoimmune disease (lupus, RA), or recovery from acute infection. Monocytosis warrants investigation if persistent.',
        'high_meaning_bg': 'Хронична инфекция, възпаление, автоимунно заболяване или възстановяване от остра инфекция. Моноцитозата изисква изследване ако е постоянна.',
        'low_meaning': 'Usually not significant alone. Can be from bone marrow issues or immunosuppression.',
        'low_meaning_bg': 'Обикновено не е значително само по себе си. Може да е от проблеми с костния мозък.',
        'improve_tips': ['Address chronic infections or inflammation', 'Anti-inflammatory diet may help normalize', 'If persistently elevated, see a hematologist', 'Moderate exercise and stress management'],
        'improve_tips_bg': ['Адресирайте хронични инфекции или възпаление', 'Противовъзпалителна диета може да помогне', 'Ако е постоянно повишен, посетете хематолог'],
        'sort_order': 12,
    },

    # ── LIPID PANEL ──────────────────────────────────────────────────
    {
        'category': 'lipid_panel', 'abbreviation': 'CHOL', 'name': 'Total Cholesterol', 'name_bg': 'Общ холестерол',
        'unit': 'mmol/L', 'alt_units': [{'unit': 'mg/dL', 'factor': 38.67}],
        'aliases': ['Cholesterol', 'Total Cholesterol', 'Холестерол', 'Общ холестерол', 'TC', 'CHOL'],
        'ref_min_male': 0, 'ref_max_male': 5.2, 'ref_min_female': 0, 'ref_max_female': 5.2,
        'optimal_min': 3.5, 'optimal_max': 5.0, 'critical_low': None, 'critical_high': 8.0,
        'description': 'Total amount of cholesterol in blood. Includes LDL, HDL, and VLDL. A key cardiovascular risk marker.',
        'description_bg': 'Общо количество холестерол в кръвта. Включва LDL, HDL и VLDL. Ключов маркер за сърдечно-съдов риск.',
        'high_meaning': 'Increased cardiovascular risk. Look at LDL/HDL ratio for full picture. Diet and genetics both contribute.',
        'high_meaning_bg': 'Повишен сърдечно-съдов риск. Вижте съотношението LDL/HDL за пълна картина.',
        'low_meaning': 'Very low cholesterol may indicate liver disease, malnutrition, or hyperthyroidism.',
        'low_meaning_bg': 'Много нисък холестерол може да означава чернодробно заболяване, недохранване или хипертиреоидизъм.',
        'improve_tips': ['Reduce saturated fats: less red meat, butter, cheese', 'Eat more fiber: oats, beans, fruits', 'Exercise 30 min/day', 'Add omega-3: fish, walnuts, flaxseed', 'Limit alcohol'],
        'improve_tips_bg': ['Намалете наситените мазнини: по-малко червено месо, масло, сирене', 'Яжте повече фибри: овесени ядки, боб, плодове', 'Упражнения 30 мин/ден', 'Добавете омега-3: риба, орехи, ленено семе', 'Ограничете алкохола'],
        'sort_order': 1,
    },
    {
        'category': 'lipid_panel', 'abbreviation': 'LDL', 'name': 'LDL Cholesterol', 'name_bg': 'LDL холестерол',
        'unit': 'mmol/L', 'alt_units': [{'unit': 'mg/dL', 'factor': 38.67}],
        'aliases': ['LDL', 'LDL-C', 'LDL Cholesterol', 'LDL холестерол', 'Low density'],
        'ref_min_male': 0, 'ref_max_male': 3.4, 'ref_min_female': 0, 'ref_max_female': 3.4,
        'optimal_min': 1.0, 'optimal_max': 2.6, 'critical_low': None, 'critical_high': 5.0,
        'description': '"Bad" cholesterol — deposits in artery walls. Primary target for cardiovascular risk reduction.',
        'description_bg': '"Лош" холестерол — отлага се по стените на артериите. Основна цел за намаляване на сърдечно-съдовия риск.',
        'high_meaning': 'Major risk factor for heart disease and stroke. Diet, exercise, and sometimes statins needed.',
        'high_meaning_bg': 'Основен рисков фактор за сърдечни заболявания и инсулт.',
        'low_meaning': 'Generally good. Very low levels are rare and usually not concerning.',
        'low_meaning_bg': 'Като цяло добре. Много ниските нива са редки и обикновено не са притеснителни.',
        'improve_tips': ['Plant sterols: 2g/day lowers LDL 10%', 'Soluble fiber: oats, barley, beans', 'Replace saturated with unsaturated fats', 'Regular aerobic exercise', 'Maintain healthy weight'],
        'improve_tips_bg': ['Растителни стероли: 2г/ден намалява LDL с 10%', 'Разтворими фибри: овес, ечемик, боб', 'Заменете наситените с ненаситени мазнини', 'Редовни аеробни упражнения', 'Поддържайте здравословно тегло'],
        'sort_order': 2,
    },
    {
        'category': 'lipid_panel', 'abbreviation': 'HDL', 'name': 'HDL Cholesterol', 'name_bg': 'HDL холестерол',
        'unit': 'mmol/L', 'alt_units': [{'unit': 'mg/dL', 'factor': 38.67}],
        'aliases': ['HDL', 'HDL-C', 'HDL Cholesterol', 'HDL холестерол', 'High density'],
        'ref_min_male': 1.0, 'ref_max_male': 100, 'ref_min_female': 1.2, 'ref_max_female': 100,
        'optimal_min': 1.5, 'optimal_max': 2.5, 'critical_low': 0.5, 'critical_high': None,
        'description': '"Good" cholesterol — removes LDL from arteries. Higher is better for heart protection.',
        'description_bg': '"Добър" холестерол — премахва LDL от артериите. По-високото е по-добре за защита на сърцето.',
        'high_meaning': 'Protective against heart disease. Very high (>2.5) may warrant genetic testing.',
        'high_meaning_bg': 'Защитен срещу сърдечни заболявания.',
        'low_meaning': 'Increased cardiovascular risk. Common with sedentary lifestyle, smoking, poor diet.',
        'low_meaning_bg': 'Повишен сърдечно-съдов риск. Често при заседнал начин на живот, тютюнопушене, лоша диета.',
        'improve_tips': ['Exercise regularly — most effective HDL booster', 'Eat healthy fats: olive oil, avocado, nuts', 'Quit smoking', 'Moderate alcohol (1 drink/day) may help', 'Lose excess weight'],
        'improve_tips_bg': ['Редовни упражнения — най-ефективният начин за повишаване на HDL', 'Яжте здравословни мазнини: зехтин, авокадо, ядки', 'Спрете тютюнопушенето', 'Умерен алкохол може да помогне', 'Свалете излишното тегло'],
        'sort_order': 3,
    },
    {
        'category': 'lipid_panel', 'abbreviation': 'TG', 'name': 'Triglycerides', 'name_bg': 'Триглицериди',
        'unit': 'mmol/L', 'alt_units': [{'unit': 'mg/dL', 'factor': 88.57}],
        'aliases': ['TG', 'Triglycerides', 'Триглицериди', 'TRIG', 'Triglycerids'],
        'ref_min_male': 0, 'ref_max_male': 1.7, 'ref_min_female': 0, 'ref_max_female': 1.7,
        'optimal_min': 0.5, 'optimal_max': 1.2, 'critical_low': None, 'critical_high': 5.6,
        'description': 'Fat in blood from food and liver production. Elevated levels increase cardiovascular and pancreatitis risk.',
        'description_bg': 'Мазнини в кръвта от храна и чернодробно производство. Повишените нива увеличават сърдечно-съдовия риск.',
        'high_meaning': 'Linked to metabolic syndrome, diabetes risk, and pancreatitis if very high. Often diet-related.',
        'high_meaning_bg': 'Свързани с метаболитен синдром, риск от диабет и панкреатит при много високи стойности.',
        'low_meaning': 'Generally fine. Very low may indicate malnutrition or hyperthyroidism.',
        'low_meaning_bg': 'Като цяло добре. Много ниски може да означава недохранване или хипертиреоидизъм.',
        'improve_tips': ['Cut sugar and refined carbs — biggest TG driver', 'Limit alcohol', 'Eat omega-3 fatty fish 2-3x/week', 'Exercise regularly', 'Lose belly fat'],
        'improve_tips_bg': ['Намалете захарта и рафинираните въглехидрати', 'Ограничете алкохола', 'Яжте риба с омега-3 2-3 пъти/седмица', 'Редовни упражнения', 'Свалете коремните мазнини'],
        'sort_order': 4,
    },

    # ── METABOLIC PANEL ──────────────────────────────────────────────
    {
        'category': 'metabolic', 'abbreviation': 'GLU', 'name': 'Glucose (Fasting)', 'name_bg': 'Глюкоза (на гладно)',
        'unit': 'mmol/L', 'alt_units': [{'unit': 'mg/dL', 'factor': 18.02}],
        'aliases': ['Glucose', 'Глюкоза', 'GLU', 'Blood sugar', 'Fasting glucose', 'Кръвна захар', 'Glu'],
        'ref_min_male': 3.9, 'ref_max_male': 6.1, 'ref_min_female': 3.9, 'ref_max_female': 6.1,
        'optimal_min': 4.0, 'optimal_max': 5.4, 'critical_low': 2.8, 'critical_high': 13.9,
        'description': 'Blood sugar level. Primary marker for diabetes screening and metabolic health.',
        'description_bg': 'Ниво на кръвната захар. Основен маркер за скрининг на диабет и метаболитно здраве.',
        'high_meaning': 'Pre-diabetes (5.6-6.9) or diabetes (≥7.0). Insulin resistance, metabolic syndrome.',
        'high_meaning_bg': 'Преддиабет (5.6-6.9) или диабет (≥7.0). Инсулинова резистентност, метаболитен синдром.',
        'low_meaning': 'Hypoglycemia — dizziness, shakiness. May indicate insulin overproduction.',
        'low_meaning_bg': 'Хипогликемия — замайване, треперене. Може да означава свръхпроизводство на инсулин.',
        'improve_tips': ['Reduce refined carbs and sugar', 'Walk 15 min after meals', 'Eat protein + fat with every meal', 'Get 7-8 hours sleep', 'Strength training improves insulin sensitivity'],
        'improve_tips_bg': ['Намалете рафинираните въглехидрати и захарта', 'Разходка 15 мин след хранене', 'Яжте протеин + мазнини с всяко хранене', 'Спете 7-8 часа', 'Силовите тренировки подобряват инсулиновата чувствителност'],
        'sort_order': 1,
    },
    {
        'category': 'metabolic', 'abbreviation': 'HBA1C', 'name': 'HbA1c', 'name_bg': 'Гликиран хемоглобин',
        'unit': '%', 'alt_units': [{'unit': 'mmol/mol', 'factor': 10.93}],
        'aliases': ['HbA1c', 'HBA1C', 'Glycated hemoglobin', 'Гликиран хемоглобин', 'A1C', 'Glycohemoglobin'],
        'ref_min_male': 4.0, 'ref_max_male': 5.6, 'ref_min_female': 4.0, 'ref_max_female': 5.6,
        'optimal_min': 4.5, 'optimal_max': 5.3, 'critical_low': None, 'critical_high': 10.0,
        'description': '3-month average blood sugar. More reliable than single glucose test for diabetes assessment.',
        'description_bg': 'Средна кръвна захар за 3 месеца. По-надежден от еднократен тест за глюкоза за оценка на диабет.',
        'high_meaning': 'Pre-diabetes (5.7-6.4%) or diabetes (≥6.5%). Indicates chronic blood sugar elevation.',
        'high_meaning_bg': 'Преддиабет (5.7-6.4%) или диабет (≥6.5%). Показва хронично повишение на кръвната захар.',
        'low_meaning': 'Usually normal. Very low may indicate frequent hypoglycemia.',
        'low_meaning_bg': 'Обикновено нормално. Много ниско може да означава чести хипогликемии.',
        'improve_tips': ['All glucose tips apply here with 3-month perspective', 'Consistent daily exercise most impactful', 'Mediterranean diet proven to lower HbA1c', 'Manage stress — cortisol raises blood sugar'],
        'improve_tips_bg': ['Всички съвети за глюкозата важат тук с 3-месечна перспектива', 'Последователни ежедневни упражнения', 'Средиземноморска диета доказано намалява HbA1c', 'Управлявайте стреса — кортизолът повишава кръвната захар'],
        'sort_order': 2,
    },

    # ── LIVER FUNCTION ───────────────────────────────────────────────
    {
        'category': 'liver', 'abbreviation': 'ALT', 'name': 'ALT (SGPT)', 'name_bg': 'АЛТ (СГПТ)',
        'unit': 'U/L', 'alt_units': [],
        'aliases': ['ALT', 'SGPT', 'АЛТ', 'СГПТ', 'Alanine aminotransferase', 'Аланин аминотрансфераза', 'GPT'],
        'ref_min_male': 0, 'ref_max_male': 41, 'ref_min_female': 0, 'ref_max_female': 33,
        'optimal_min': 7, 'optimal_max': 25, 'critical_low': None, 'critical_high': 200,
        'description': 'Liver enzyme released when liver cells are damaged. Most specific liver damage marker.',
        'description_bg': 'Чернодробен ензим, който се освобождава при увреждане на чернодробните клетки.',
        'high_meaning': 'Liver inflammation or damage — fatty liver, hepatitis, alcohol, medications, or obesity.',
        'high_meaning_bg': 'Чернодробно възпаление или увреждане — мастен черен дроб, хепатит, алкохол, лекарства или затлъстяване.',
        'low_meaning': 'Normal. Very low is not clinically significant.',
        'low_meaning_bg': 'Нормално. Много ниски стойности нямат клинично значение.',
        'improve_tips': ['Limit alcohol to 1-2 drinks/week max', 'Reduce sugar — #1 cause of fatty liver', 'Maintain healthy weight', 'Exercise regularly', 'Coffee (2-3 cups) shown to protect liver', 'Avoid unnecessary medications'],
        'improve_tips_bg': ['Ограничете алкохола до 1-2 напитки/седмица', 'Намалете захарта — №1 причина за мастен черен дроб', 'Поддържайте здравословно тегло', 'Редовни упражнения', 'Кафето (2-3 чаши) доказано защитава черния дроб'],
        'sort_order': 1,
    },
    {
        'category': 'liver', 'abbreviation': 'AST', 'name': 'AST (SGOT)', 'name_bg': 'АСТ (СГОТ)',
        'unit': 'U/L', 'alt_units': [],
        'aliases': ['AST', 'SGOT', 'АСТ', 'СГОТ', 'Aspartate aminotransferase', 'Аспартат аминотрансфераза', 'GOT'],
        'ref_min_male': 0, 'ref_max_male': 40, 'ref_min_female': 0, 'ref_max_female': 32,
        'optimal_min': 10, 'optimal_max': 26, 'critical_low': None, 'critical_high': 200,
        'description': 'Enzyme found in liver and heart muscle. Elevated with liver damage or intense exercise.',
        'description_bg': 'Ензим в черния дроб и сърдечния мускул. Повишен при чернодробно увреждане или интензивни упражнения.',
        'high_meaning': 'Liver damage, heart muscle damage, or heavy exercise in past 48h. Check ALT ratio.',
        'high_meaning_bg': 'Чернодробно увреждане, увреждане на сърдечния мускул или тежки упражнения в последните 48ч.',
        'low_meaning': 'Normal.',
        'low_meaning_bg': 'Нормално.',
        'improve_tips': ['Same as ALT tips', 'If elevated after exercise, retest after 72h rest', 'AST/ALT ratio > 2 suggests alcohol-related damage'],
        'improve_tips_bg': ['Същите съвети като за АЛТ', 'Ако е повишен след упражнения, повторете след 72ч почивка', 'Съотношение АСТ/АЛТ > 2 предполага алкохолно увреждане'],
        'sort_order': 2,
    },
    {
        'category': 'liver', 'abbreviation': 'GGT', 'name': 'GGT', 'name_bg': 'ГГТ',
        'unit': 'U/L', 'alt_units': [],
        'aliases': ['GGT', 'ГГТ', 'Gamma-GT', 'Gamma-glutamyl transferase', 'Гама-глутамил трансфераза'],
        'ref_min_male': 0, 'ref_max_male': 55, 'ref_min_female': 0, 'ref_max_female': 38,
        'optimal_min': 9, 'optimal_max': 30, 'critical_low': None, 'critical_high': 300,
        'description': 'Liver enzyme most sensitive to alcohol and bile duct obstruction. Key alcohol marker.',
        'description_bg': 'Чернодробен ензим, най-чувствителен към алкохол и обструкция на жлъчните пътища.',
        'high_meaning': 'Alcohol use, bile duct issues, fatty liver, medications. Most sensitive alcohol marker.',
        'high_meaning_bg': 'Употреба на алкохол, проблеми с жлъчните пътища, мастен черен дроб, лекарства.',
        'low_meaning': 'Normal.',
        'low_meaning_bg': 'Нормално.',
        'improve_tips': ['Reduce or eliminate alcohol', 'Lose excess weight', 'Avoid hepatotoxic medications when possible'],
        'improve_tips_bg': ['Намалете или елиминирайте алкохола', 'Свалете излишното тегло', 'Избягвайте хепатотоксични лекарства когато е възможно'],
        'sort_order': 3,
    },
    {
        'category': 'liver', 'abbreviation': 'TBIL', 'name': 'Total Bilirubin', 'name_bg': 'Общ билирубин',
        'unit': 'μmol/L', 'alt_units': [{'unit': 'mg/dL', 'factor': 17.1}],
        'aliases': ['Bilirubin', 'Билирубин', 'TBIL', 'Total bilirubin', 'Общ билирубин', 'BIL-T'],
        'ref_min_male': 3, 'ref_max_male': 21, 'ref_min_female': 3, 'ref_max_female': 21,
        'optimal_min': 5, 'optimal_max': 17, 'critical_low': None, 'critical_high': 50,
        'description': 'Byproduct of red blood cell breakdown, processed by liver. Elevated causes jaundice.',
        'description_bg': 'Страничен продукт от разграждането на червените кръвни клетки, преработван от черния дроб.',
        'high_meaning': 'Liver disease, bile duct blockage, or Gilbert syndrome (benign genetic condition, ~5% of people).',
        'high_meaning_bg': 'Чернодробно заболяване, блокада на жлъчните пътища или синдром на Жилбер (доброкачествено генетично състояние).',
        'low_meaning': 'Normal.',
        'low_meaning_bg': 'Нормално.',
        'improve_tips': ['Mildly elevated bilirubin with normal liver enzymes is often Gilbert syndrome — benign', 'Support liver health: reduce alcohol, maintain weight', 'Stay hydrated'],
        'improve_tips_bg': ['Леко повишен билирубин при нормални чернодробни ензими често е синдром на Жилбер — доброкачествен', 'Подкрепете здравето на черния дроб: намалете алкохола, поддържайте теглото'],
        'sort_order': 4,
    },

    {
        'category': 'lipid_panel', 'abbreviation': 'VLDL', 'name': 'VLDL Cholesterol', 'name_bg': 'VLDL холестерол',
        'unit': 'mmol/L', 'alt_units': [{'unit': 'mg/dL', 'factor': 38.67}],
        'aliases': ['VLDL', 'VLDL-C', 'VLDL Cholesterol', 'VLDL холестерол', 'VLDL-Холестерол', 'Very low density'],
        'ref_min_male': 0, 'ref_max_male': 0.9, 'ref_min_female': 0, 'ref_max_female': 0.9,
        'optimal_min': 0.1, 'optimal_max': 0.7, 'critical_low': None, 'critical_high': 3.0,
        'description': 'Carries triglycerides from the liver to tissues. High VLDL strongly correlates with high triglycerides and metabolic syndrome.',
        'description_bg': 'Пренася триглицериди от черния дроб към тъканите. Висок VLDL силно корелира с високи триглицериди и метаболитен синдром.',
        'high_meaning': 'Excess triglyceride transport — usually from high-carb diet, obesity, or insulin resistance. Contributes to atherosclerosis.',
        'high_meaning_bg': 'Излишен транспорт на триглицериди — обикновено от високовъглехидратна диета, затлъстяване или инсулинова резистентност.',
        'low_meaning': 'Normal — indicates good triglyceride metabolism.',
        'low_meaning_bg': 'Нормално — показва добър метаболизъм на триглицеридите.',
        'improve_tips': ['Same as triglyceride tips: cut sugar and refined carbs', 'Exercise burns triglycerides directly', 'Omega-3 fatty acids (fish oil) lower VLDL', 'Limit alcohol'],
        'improve_tips_bg': ['Същите съвети като за триглицериди: намалете захарта и рафинираните въглехидрати', 'Упражненията изгарят триглицеридите директно', 'Омега-3 мастни киселини (рибено масло) намаляват VLDL'],
        'sort_order': 5,
    },

    # ── METABOLIC PANEL ──────────────────────────────────────────────────
    # (Glucose and HbA1c already above)

    # ── LIVER FUNCTION ───────────────────────────────────────────────────
    # (ALT, AST, GGT, TBIL already defined — adding ALP, Direct Bilirubin)

    {
        'category': 'liver', 'abbreviation': 'ALP', 'name': 'Alkaline Phosphatase', 'name_bg': 'Алкална фосфатаза (АФ)',
        'unit': 'U/L', 'alt_units': [],
        'aliases': ['ALP', 'Alkaline phosphatase', 'АФ', 'Алкална фосфатаза', 'AP'],
        'ref_min_male': 40, 'ref_max_male': 130, 'ref_min_female': 35, 'ref_max_female': 105,
        'optimal_min': 50, 'optimal_max': 100, 'critical_low': None, 'critical_high': 500,
        'description': 'Enzyme found in liver, bone, kidney, and gut. Elevated in liver or bone disease. Important to interpret alongside other liver enzymes.',
        'description_bg': 'Ензим в черния дроб, костите, бъбреците и червата. Повишен при чернодробно или костно заболяване. Важно да се интерпретира заедно с другите чернодробни ензими.',
        'high_meaning': 'Bile duct obstruction, liver disease, bone disease (Paget\'s, fracture healing), or growing children/teens (normal). With elevated GGT → liver origin; with normal GGT → bone origin.',
        'high_meaning_bg': 'Обструкция на жлъчните пътища, чернодробно заболяване, костно заболяване. С повишен ГГТ → чернодробен произход; с нормален ГГТ → костен произход.',
        'low_meaning': 'Malnutrition, zinc deficiency, hypothyroidism, or pernicious anemia. Rarely clinically significant.',
        'low_meaning_bg': 'Недохранване, дефицит на цинк, хипотиреоидизъм. Рядко клинично значимо.',
        'improve_tips': ['Interpret with GGT: both high = liver issue', 'Maintain bone health: weight-bearing exercise, vitamin D, calcium', 'Zinc supplementation if deficient may help normalize', 'Reduce alcohol for liver-related elevation'],
        'improve_tips_bg': ['Интерпретирайте с ГГТ: и двата високи = чернодробен проблем', 'Поддържайте костното здраве: упражнения с тежести, витамин D, калций', 'Намалете алкохола при чернодробно повишение'],
        'sort_order': 5,
    },
    {
        'category': 'liver', 'abbreviation': 'DBIL', 'name': 'Direct Bilirubin', 'name_bg': 'Директен билирубин',
        'unit': 'μmol/L', 'alt_units': [{'unit': 'mg/dL', 'factor': 17.1}],
        'aliases': ['Direct bilirubin', 'Директен билирубин', 'DBIL', 'Bilirubin direct', 'D-BIL'],
        'ref_min_male': 0, 'ref_max_male': 8.0, 'ref_min_female': 0, 'ref_max_female': 8.0,
        'optimal_min': 0, 'optimal_max': 5.0, 'critical_low': None, 'critical_high': 30,
        'description': 'Bilirubin that has been processed (conjugated) by the liver. High direct bilirubin specifically points to liver or bile duct problems, unlike total bilirubin.',
        'description_bg': 'Билирубин, който е бил обработен (конюгиран) от черния дроб. Висок директен билирубин специфично сочи към чернодробни проблеми или проблеми с жлъчните пътища.',
        'high_meaning': 'Bile duct obstruction (gallstones, tumor), hepatitis, or drug-induced liver injury. If direct/total ratio > 50% → obstructive cause.',
        'high_meaning_bg': 'Обструкция на жлъчните пътища (жлъчни камъни, тумор), хепатит или лекарствено-индуцирано чернодробно увреждане.',
        'low_meaning': 'Normal.',
        'low_meaning_bg': 'Нормално.',
        'improve_tips': ['Seek medical evaluation if elevated — may indicate obstruction', 'Liver-supportive lifestyle: reduce alcohol, avoid hepatotoxic drugs', 'Ultrasound recommended if consistently elevated'],
        'improve_tips_bg': ['Потърсете медицинска оценка при повишение — може да означава обструкция', 'Чернодробно-подкрепящ начин на живот: намалете алкохола'],
        'sort_order': 6,
    },

    # ── PROTEIN PANEL (new category) ─────────────────────────────────

    {
        'category': 'proteins', 'abbreviation': 'TP', 'name': 'Total Protein', 'name_bg': 'Общ белтък',
        'unit': 'g/L', 'alt_units': [{'unit': 'g/dL', 'factor': 0.1}],
        'aliases': ['Total protein', 'Общ белтък', 'TP', 'Protein total', 'Общ протеин'],
        'ref_min_male': 60, 'ref_max_male': 83, 'ref_min_female': 60, 'ref_max_female': 83,
        'optimal_min': 65, 'optimal_max': 80, 'critical_low': 40, 'critical_high': 100,
        'description': 'Total amount of albumin and globulin proteins in blood. Reflects liver function (production), kidney function (loss), and nutritional status.',
        'description_bg': 'Общо количество албумин и глобулин протеини в кръвта. Отразява чернодробната функция (производство), бъбречната функция (загуба) и хранителния статус.',
        'high_meaning': 'Dehydration (most common), chronic infection, or multiple myeloma. Usually rechecked after hydration.',
        'high_meaning_bg': 'Дехидратация (най-честа причина), хронична инфекция или мултиплен миелом. Обикновено се проверява отново след хидратация.',
        'low_meaning': 'Liver disease (reduced production), kidney disease (protein loss), malnutrition, or malabsorption.',
        'low_meaning_bg': 'Чернодробно заболяване (намалено производство), бъбречно заболяване (загуба на протеин), недохранване.',
        'improve_tips': ['Ensure adequate protein intake: 1.2-1.6g per kg body weight', 'Spread protein across meals (30g per meal ideal)', 'If low: check liver and kidney function', 'Stay hydrated if high'],
        'improve_tips_bg': ['Осигурете адекватен прием на протеин: 1.2-1.6г на кг телесно тегло', 'Разпределете протеина равномерно в храненията', 'Ако е нисък: проверете чернодробната и бъбречна функция'],
        'sort_order': 1,
    },
    {
        'category': 'proteins', 'abbreviation': 'ALB', 'name': 'Albumin', 'name_bg': 'Албумин',
        'unit': 'g/L', 'alt_units': [{'unit': 'g/dL', 'factor': 0.1}],
        'aliases': ['Albumin', 'Албумин', 'ALB', 'Serum albumin'],
        'ref_min_male': 35, 'ref_max_male': 55, 'ref_min_female': 35, 'ref_max_female': 55,
        'optimal_min': 40, 'optimal_max': 50, 'critical_low': 25, 'critical_high': None,
        'description': 'Most abundant blood protein, made by the liver. Carries hormones, drugs, and nutrients. A key marker of liver health and nutritional status.',
        'description_bg': 'Най-разпространеният кръвен протеин, произвеждан от черния дроб. Пренася хормони, лекарства и хранителни вещества. Ключов маркер за здравето на черния дроб.',
        'high_meaning': 'Usually dehydration. True hyperalbuminemia is very rare.',
        'high_meaning_bg': 'Обикновено дехидратация. Истинска хипералбуминемия е много рядка.',
        'low_meaning': 'Liver disease (#1 producer), kidney disease (nephrotic syndrome loses albumin), malnutrition, or chronic inflammation. Low albumin = poor prognosis in hospitalized patients.',
        'low_meaning_bg': 'Чернодробно заболяване (#1 производител), бъбречно заболяване, недохранване или хронично възпаление. Нисък албумин = лоша прогноза при хоспитализирани пациенти.',
        'improve_tips': ['Adequate protein intake is essential', 'Treat underlying liver or kidney disease', 'Albumin < 35 g/L warrants medical investigation', 'Reduce inflammation (anti-inflammatory diet + exercise)'],
        'improve_tips_bg': ['Адекватен прием на протеин е задължителен', 'Лекувайте основното чернодробно или бъбречно заболяване', 'Албумин < 35 g/L изисква медицинско изследване'],
        'sort_order': 2,
    },

    # ── TUMOR MARKERS (new category) ─────────────────────────────────

    {
        'category': 'tumor_markers', 'abbreviation': 'PSA', 'name': 'Total PSA', 'name_bg': 'Общ ПСА',
        'unit': 'ng/mL', 'alt_units': [],
        'aliases': ['PSA', 'total PSA', 'Общ ПСА', 'Prostate specific antigen', 'Простатспецифичен антиген'],
        'ref_min_male': 0, 'ref_max_male': 4.0, 'ref_min_female': None, 'ref_max_female': None,
        'optimal_min': 0, 'optimal_max': 2.0, 'critical_low': None, 'critical_high': 10,
        'description': 'Prostate-Specific Antigen — a protein produced by the prostate gland. Used for prostate cancer screening, but also elevated in benign conditions.',
        'description_bg': 'Простатспецифичен антиген — протеин, произвеждан от простатната жлеза. Използва се за скрининг на рак на простатата, но е повишен и при доброкачествени състояния.',
        'high_meaning': 'Prostate cancer (possible but not definitive), benign prostatic hyperplasia (BPH), prostatitis, recent ejaculation, or cycling. PSA 4-10 = "grey zone" requiring further testing (free PSA ratio, MRI).',
        'high_meaning_bg': 'Рак на простатата (възможен но не дефинитивен), доброкачествена простатна хиперплазия (ДПХ), простатит. ПСА 4-10 = "сива зона" изискваща допълнителни тестове.',
        'low_meaning': 'Normal — no concern.',
        'low_meaning_bg': 'Нормално — няма притеснение.',
        'improve_tips': ['Avoid ejaculation 48h before test for accurate reading', 'Avoid cycling 48h before test', 'If elevated: free PSA ratio, MRI, then biopsy if needed', 'Lycopene (tomatoes) and green tea may support prostate health', 'Annual PSA screening recommended after age 50 (or 45 with family history)'],
        'improve_tips_bg': ['Избягвайте еякулация 48ч преди теста за точен резултат', 'Избягвайте колоездене 48ч преди теста', 'При повишен: съотношение свободен ПСА, МРТ, биопсия ако е нужна', 'Ликопен (домати) и зелен чай подпомагат здравето на простатата'],
        'sort_order': 1,
    },
    {
        'category': 'tumor_markers', 'abbreviation': 'CEA', 'name': 'Carcinoembryonic Antigen', 'name_bg': 'Карциноембрионален антиген',
        'unit': 'ng/mL', 'alt_units': [],
        'aliases': ['CEA', 'Carcinoembryonic antigen', 'Карциноембрионален антиген'],
        'ref_min_male': 0, 'ref_max_male': 3.8, 'ref_min_female': 0, 'ref_max_female': 3.8,
        'optimal_min': 0, 'optimal_max': 2.5, 'critical_low': None, 'critical_high': 20,
        'description': 'A protein used as a tumor marker, mainly for monitoring colorectal cancer treatment. Also elevated in smokers and some non-cancerous conditions.',
        'description_bg': 'Протеин, използван като туморен маркер, главно за проследяване на лечението на колоректален рак. Повишен и при пушачи.',
        'high_meaning': 'Colorectal, pancreatic, lung, or breast cancer (monitoring, not screening). Also elevated in smokers (up to 5.5), IBD, liver cirrhosis, and chronic inflammation.',
        'high_meaning_bg': 'Колоректален, панкреатичен, белодробен или рак на гърдата (проследяване, не скрининг). Повишен и при пушачи, IBD, чернодробна цироза.',
        'low_meaning': 'Normal — good sign especially if monitoring after cancer treatment.',
        'low_meaning_bg': 'Нормално — добър знак особено при проследяване след лечение на рак.',
        'improve_tips': ['Stop smoking — normalizes CEA within months', 'Used for monitoring, not screening — dont panic over mild elevation', 'If rising trend: colonoscopy and further workup', 'Maintain healthy weight and anti-inflammatory diet'],
        'improve_tips_bg': ['Спрете тютюнопушенето — нормализира CEA в рамките на месеци', 'Използва се за проследяване, не за скрининг — не се паникьосвайте при леко повишение'],
        'sort_order': 2,
    },
    {
        'category': 'tumor_markers', 'abbreviation': 'CA199', 'name': 'CA 19-9', 'name_bg': 'CA 19-9',
        'unit': 'U/mL', 'alt_units': [],
        'aliases': ['CA 19-9', 'CA-19-9', 'CA -19 -9', 'CA199'],
        'ref_min_male': 0, 'ref_max_male': 34, 'ref_min_female': 0, 'ref_max_female': 34,
        'optimal_min': 0, 'optimal_max': 27, 'critical_low': None, 'critical_high': 100,
        'description': 'Tumor marker primarily for pancreatic cancer monitoring. Also elevated in bile duct, gastric, and ovarian cancers. Not a screening test.',
        'description_bg': 'Туморен маркер предимно за проследяване на рак на панкреаса. Повишен и при рак на жлъчните пътища, стомаха и яйчниците. Не е скринингов тест.',
        'high_meaning': 'Pancreatic cancer (monitoring), bile duct obstruction, pancreatitis, liver cirrhosis, or cholangitis. ~5% of people genetically cannot produce CA 19-9 (Lewis antigen negative).',
        'high_meaning_bg': 'Рак на панкреаса (проследяване), обструкция на жлъчните пътища, панкреатит, чернодробна цироза.',
        'low_meaning': 'Normal.',
        'low_meaning_bg': 'Нормално.',
        'improve_tips': ['Used for monitoring pancreatic cancer, not screening', 'Mild elevation often benign — biliary or pancreatic inflammation', 'If elevated with symptoms: CT/MRI of abdomen'],
        'improve_tips_bg': ['Използва се за проследяване на рак на панкреаса, не за скрининг', 'Леко повишение често е доброкачествено', 'При повишение със симптоми: CT/МРТ на корема'],
        'sort_order': 3,
    },

    # ── KIDNEY FUNCTION ──────────────────────────────────────────────
    {
        'category': 'kidney', 'abbreviation': 'CREA', 'name': 'Creatinine', 'name_bg': 'Креатинин',
        'unit': 'μmol/L', 'alt_units': [{'unit': 'mg/dL', 'factor': 88.42}],
        'aliases': ['Creatinine', 'Креатинин', 'CREA', 'Creat'],
        'ref_min_male': 62, 'ref_max_male': 106, 'ref_min_female': 44, 'ref_max_female': 80,
        'optimal_min': 70, 'optimal_max': 95, 'critical_low': None, 'critical_high': 350,
        'description': 'Waste product from muscle metabolism, filtered by kidneys. Key kidney function indicator.',
        'description_bg': 'Отпадъчен продукт от мускулния метаболизъм, филтриран от бъбреците. Ключов индикатор за бъбречна функция.',
        'high_meaning': 'Reduced kidney function, dehydration, or high muscle mass. Recheck with eGFR.',
        'high_meaning_bg': 'Намалена бъбречна функция, дехидратация или висока мускулна маса. Проверете с eGFR.',
        'low_meaning': 'Low muscle mass or high fluid intake. Usually not concerning.',
        'low_meaning_bg': 'Ниска мускулна маса или висок прием на течности. Обикновено не е притеснително.',
        'improve_tips': ['Stay hydrated — drink 2L water/day', 'Monitor blood pressure', 'Limit excessive protein intake if kidney issues', 'Reduce sodium', 'Avoid NSAIDs long-term'],
        'improve_tips_bg': ['Пийте достатъчно вода — 2л/ден', 'Следете кръвното налягане', 'Ограничете прекомерния прием на протеин при бъбречни проблеми', 'Намалете солта'],
        'sort_order': 1,
    },
    {
        'category': 'kidney', 'abbreviation': 'UREA', 'name': 'Urea (BUN)', 'name_bg': 'Урея',
        'unit': 'mmol/L', 'alt_units': [{'unit': 'mg/dL', 'factor': 2.8}],
        'aliases': ['Urea', 'Урея', 'BUN', 'Blood urea nitrogen', 'Urea nitrogen'],
        'ref_min_male': 2.5, 'ref_max_male': 7.1, 'ref_min_female': 2.5, 'ref_max_female': 7.1,
        'optimal_min': 3.0, 'optimal_max': 6.0, 'critical_low': None, 'critical_high': 30,
        'description': 'Waste product from protein breakdown, filtered by kidneys. Reflects kidney function and protein intake.',
        'description_bg': 'Отпадъчен продукт от разграждането на протеини, филтриран от бъбреците.',
        'high_meaning': 'Kidney dysfunction, dehydration, high protein diet, or GI bleeding.',
        'high_meaning_bg': 'Бъбречна дисфункция, дехидратация, високопротеинова диета или ГИ кървене.',
        'low_meaning': 'Low protein diet or liver disease.',
        'low_meaning_bg': 'Нископротеинова диета или чернодробно заболяване.',
        'improve_tips': ['Balance protein intake', 'Stay hydrated', 'Monitor kidney function with creatinine and eGFR together'],
        'improve_tips_bg': ['Балансирайте приема на протеин', 'Пийте достатъчно вода', 'Следете бъбречната функция заедно с креатинин и eGFR'],
        'sort_order': 2,
    },
    {
        'category': 'kidney', 'abbreviation': 'URIC', 'name': 'Uric Acid', 'name_bg': 'Пикочна киселина',
        'unit': 'μmol/L', 'alt_units': [{'unit': 'mg/dL', 'factor': 59.48}],
        'aliases': ['Uric acid', 'Пикочна киселина', 'UA', 'URIC'],
        'ref_min_male': 200, 'ref_max_male': 430, 'ref_min_female': 140, 'ref_max_female': 360,
        'optimal_min': 200, 'optimal_max': 360, 'critical_low': None, 'critical_high': 600,
        'description': 'Byproduct of purine metabolism. High levels cause gout and kidney stones.',
        'description_bg': 'Страничен продукт от пуриновия метаболизъм. Високите нива причиняват подагра и бъбречни камъни.',
        'high_meaning': 'Risk of gout, kidney stones. Associated with metabolic syndrome and cardiovascular risk.',
        'high_meaning_bg': 'Риск от подагра, бъбречни камъни. Свързано с метаболитен синдром и сърдечно-съдов риск.',
        'low_meaning': 'Usually not concerning. May indicate low purine diet.',
        'low_meaning_bg': 'Обикновено не е притеснително. Може да означава нископуринова диета.',
        'improve_tips': ['Reduce purine-rich foods: organ meats, sardines, beer', 'Drink plenty of water', 'Limit fructose and alcohol', 'Cherry extract may help lower uric acid', 'Maintain healthy weight'],
        'improve_tips_bg': ['Намалете храни богати на пурини: карантии, сардини, бира', 'Пийте много вода', 'Ограничете фруктозата и алкохола', 'Екстракт от череши може да помогне', 'Поддържайте здравословно тегло'],
        'sort_order': 3,
    },

    # ── THYROID ───────────────────────────────────────────────────────
    {
        'category': 'thyroid', 'abbreviation': 'TSH', 'name': 'TSH', 'name_bg': 'ТСХ',
        'unit': 'mIU/L', 'alt_units': [{'unit': 'μIU/mL', 'factor': 1}],
        'aliases': ['TSH', 'ТСХ', 'Thyroid stimulating hormone', 'Тиреостимулиращ хормон', 'Thyrotropin'],
        'ref_min_male': 0.4, 'ref_max_male': 4.0, 'ref_min_female': 0.4, 'ref_max_female': 4.0,
        'optimal_min': 1.0, 'optimal_max': 2.5, 'critical_low': 0.01, 'critical_high': 10.0,
        'description': 'Brain hormone that controls thyroid gland. Master regulator of metabolism, energy, and weight.',
        'description_bg': 'Мозъчен хормон, който контролира щитовидната жлеза. Основен регулатор на метаболизма, енергията и теглото.',
        'high_meaning': 'Hypothyroidism (underactive thyroid) — fatigue, weight gain, cold intolerance, depression.',
        'high_meaning_bg': 'Хипотиреоидизъм (недостатъчно активна щитовидна жлеза) — умора, наддаване на тегло, непоносимост към студ.',
        'low_meaning': 'Hyperthyroidism (overactive thyroid) — weight loss, anxiety, rapid heart rate, tremor.',
        'low_meaning_bg': 'Хипертиреоидизъм (свръхактивна щитовидна жлеза) — загуба на тегло, тревожност, ускорен пулс.',
        'improve_tips': ['Get selenium: Brazil nuts (2/day), fish, eggs', 'Ensure adequate iodine (but not excessive)', 'Manage stress — affects thyroid function', 'Check thyroid antibodies if borderline', 'Avoid excessive soy and raw cruciferous vegetables'],
        'improve_tips_bg': ['Приемайте селен: бразилски орехи (2/ден), риба, яйца', 'Осигурете адекватен йод (но не прекомерен)', 'Управлявайте стреса — влияе на функцията на щитовидната жлеза'],
        'sort_order': 1,
    },
    {
        'category': 'thyroid', 'abbreviation': 'FT4', 'name': 'Free T4', 'name_bg': 'Свободен Т4',
        'unit': 'pmol/L', 'alt_units': [{'unit': 'ng/dL', 'factor': 12.87}],
        'aliases': ['FT4', 'Free T4', 'Свободен Т4', 'Thyroxine', 'Тироксин', 'fT4'],
        'ref_min_male': 10, 'ref_max_male': 22, 'ref_min_female': 10, 'ref_max_female': 22,
        'optimal_min': 13, 'optimal_max': 18, 'critical_low': 5, 'critical_high': 40,
        'description': 'Active thyroid hormone in blood. Works with TSH to assess thyroid function.',
        'description_bg': 'Активен тиреоиден хормон в кръвта. Работи заедно с ТСХ за оценка на функцията на щитовидната жлеза.',
        'high_meaning': 'Hyperthyroidism or excessive thyroid medication.',
        'high_meaning_bg': 'Хипертиреоидизъм или прекомерна доза тиреоидни лекарства.',
        'low_meaning': 'Hypothyroidism — especially significant if TSH is also high.',
        'low_meaning_bg': 'Хипотиреоидизъм — особено значимо ако ТСХ също е висок.',
        'improve_tips': ['Interpret with TSH — both needed for full picture', 'Selenium helps T4→T3 conversion', 'Iron deficiency impairs thyroid function'],
        'improve_tips_bg': ['Интерпретирайте заедно с ТСХ — и двата са нужни за пълна картина', 'Селенът помага за конверсията T4→T3', 'Дефицитът на желязо нарушава функцията на щитовидната жлеза'],
        'sort_order': 2,
    },

    # ── VITAMINS & MINERALS ──────────────────────────────────────────
    {
        'category': 'vitamins', 'abbreviation': 'VITD', 'name': 'Vitamin D (25-OH)', 'name_bg': 'Витамин Д (25-OH)',
        'unit': 'nmol/L', 'alt_units': [{'unit': 'ng/mL', 'factor': 2.496}],
        'aliases': ['Vitamin D', 'Витамин Д', '25-OH', '25-hydroxyvitamin D', 'VITD', 'Vit D', '25(OH)D'],
        'ref_min_male': 50, 'ref_max_male': 125, 'ref_min_female': 50, 'ref_max_female': 125,
        'optimal_min': 75, 'optimal_max': 100, 'critical_low': 12, 'critical_high': 250,
        'description': 'Essential for bones, immunity, mood, and muscle function. Most people in Bulgaria are deficient in winter.',
        'description_bg': 'Важен за костите, имунитета, настроението и мускулната функция. Повечето хора в България имат дефицит през зимата.',
        'high_meaning': 'Toxicity (rare) — only from excessive supplementation, not sun. Causes calcium buildup.',
        'high_meaning_bg': 'Токсичност (рядко) — само от прекомерна суплементация, не от слънце.',
        'low_meaning': 'Extremely common. Causes fatigue, bone loss, depression, weak immunity, muscle pain.',
        'low_meaning_bg': 'Изключително често. Причинява умора, загуба на костна маса, депресия, слаб имунитет, мускулна болка.',
        'improve_tips': ['Supplement 2000-4000 IU daily (Oct-Apr in Bulgaria)', 'Take with fat for absorption', '15-20 min sun exposure (arms/face) in summer', 'Fatty fish, egg yolks, fortified foods', 'Retest after 3 months of supplementation'],
        'improve_tips_bg': ['Суплементирайте 2000-4000 IU дневно (Окт-Апр в България)', 'Приемайте с мазнини за по-добра абсорбция', '15-20 мин слънце (ръце/лице) лятото', 'Мастна риба, жълтъци, обогатени храни', 'Повторете теста след 3 месеца суплементация'],
        'sort_order': 1,
    },
    {
        'category': 'vitamins', 'abbreviation': 'B12', 'name': 'Vitamin B12', 'name_bg': 'Витамин B12',
        'unit': 'pmol/L', 'alt_units': [{'unit': 'pg/mL', 'factor': 0.738}],
        'aliases': ['B12', 'Vitamin B12', 'Витамин B12', 'Cobalamin', 'Кобаламин'],
        'ref_min_male': 145, 'ref_max_male': 569, 'ref_min_female': 145, 'ref_max_female': 569,
        'optimal_min': 300, 'optimal_max': 500, 'critical_low': 100, 'critical_high': None,
        'description': 'Essential for nerve function, DNA synthesis, and red blood cell formation. Stored in liver for years.',
        'description_bg': 'Важен за нервната функция, синтеза на ДНК и образуването на червени кръвни клетки.',
        'high_meaning': 'Usually from supplementation. Rarely indicates liver disease or blood cancer.',
        'high_meaning_bg': 'Обикновено от суплементация. Рядко указва чернодробно заболяване.',
        'low_meaning': 'Nerve damage, anemia, fatigue, memory issues. Common in vegetarians/vegans and elderly.',
        'low_meaning_bg': 'Увреждане на нервите, анемия, умора, проблеми с паметта. Често при вегетарианци/веганисти и възрастни.',
        'improve_tips': ['Animal foods: meat, fish, eggs, dairy', 'Vegans: supplement 1000mcg methylcobalamin daily', 'Sublingual B12 bypasses absorption issues', 'If very low, start with injections then oral'],
        'improve_tips_bg': ['Животински храни: месо, риба, яйца, млечни продукти', 'Веганисти: суплементирайте 1000мкг метилкобаламин дневно', 'Сублингвален B12 заобикаля проблемите с абсорбцията'],
        'sort_order': 2,
    },
    {
        'category': 'vitamins', 'abbreviation': 'FOLATE', 'name': 'Folate (Folic Acid)', 'name_bg': 'Фолат (Фолиева киселина)',
        'unit': 'nmol/L', 'alt_units': [{'unit': 'ng/mL', 'factor': 2.266}],
        'aliases': ['Folate', 'Фолат', 'Folic acid', 'Фолиева киселина', 'B9', 'Vitamin B9'],
        'ref_min_male': 7, 'ref_max_male': 45, 'ref_min_female': 7, 'ref_max_female': 45,
        'optimal_min': 15, 'optimal_max': 35, 'critical_low': 3, 'critical_high': None,
        'description': 'B vitamin essential for DNA synthesis and cell division. Critical during pregnancy.',
        'description_bg': 'Витамин от група B, важен за синтеза на ДНК и клетъчното делене. Критичен по време на бременност.',
        'high_meaning': 'Usually from supplementation. Not harmful.',
        'high_meaning_bg': 'Обикновено от суплементация. Не е вредно.',
        'low_meaning': 'Anemia, fatigue, mouth sores, neural tube defects in pregnancy.',
        'low_meaning_bg': 'Анемия, умора, язви в устата, дефекти на нервната тръба при бременност.',
        'improve_tips': ['Dark leafy greens: spinach, kale, broccoli', 'Legumes: lentils, chickpeas, beans', 'Fortified cereals', 'Supplement 400-800mcg methylfolate if deficient'],
        'improve_tips_bg': ['Тъмни листни зеленчуци: спанак, кейл, броколи', 'Бобови: леща, нахут, боб', 'Обогатени зърнени храни', 'Суплементирайте 400-800мкг метилфолат при дефицит'],
        'sort_order': 3,
    },
    {
        'category': 'vitamins', 'abbreviation': 'MG', 'name': 'Magnesium', 'name_bg': 'Магнезий',
        'unit': 'mmol/L', 'alt_units': [{'unit': 'mg/dL', 'factor': 2.431}],
        'aliases': ['Magnesium', 'Магнезий', 'Mg', 'MG'],
        'ref_min_male': 0.7, 'ref_max_male': 1.0, 'ref_min_female': 0.7, 'ref_max_female': 1.0,
        'optimal_min': 0.8, 'optimal_max': 0.95, 'critical_low': 0.4, 'critical_high': 2.0,
        'description': 'Essential mineral for 300+ enzyme reactions. Affects muscles, nerves, blood sugar, and blood pressure.',
        'description_bg': 'Важен минерал за 300+ ензимни реакции. Влияе на мускулите, нервите, кръвната захар и кръвното налягане.',
        'high_meaning': 'Kidney dysfunction or excessive supplementation.',
        'high_meaning_bg': 'Бъбречна дисфункция или прекомерна суплементация.',
        'low_meaning': 'Very common deficiency. Muscle cramps, poor sleep, anxiety, heart palpitations.',
        'low_meaning_bg': 'Много чест дефицит. Мускулни крампи, лош сън, тревожност, сърцебиене.',
        'improve_tips': ['Supplement magnesium glycinate 200-400mg before bed', 'Dark chocolate (70%+), nuts, seeds, legumes', 'Epsom salt baths for transdermal absorption', 'Alcohol and stress deplete magnesium'],
        'improve_tips_bg': ['Суплементирайте магнезиев глицинат 200-400мг преди сън', 'Тъмен шоколад (70%+), ядки, семена, бобови', 'Бани с английска сол за трансдермална абсорбция', 'Алкохолът и стресът изчерпват магнезия'],
        'sort_order': 4,
    },

    # ── IRON STUDIES ─────────────────────────────────────────────────
    {
        'category': 'iron_studies', 'abbreviation': 'FE', 'name': 'Serum Iron', 'name_bg': 'Серумно желязо',
        'unit': 'μmol/L', 'alt_units': [{'unit': 'μg/dL', 'factor': 5.585}],
        'aliases': ['Iron', 'Желязо', 'Серумно желязо', 'Fe', 'Serum iron', 'FE'],
        'ref_min_male': 11, 'ref_max_male': 28, 'ref_min_female': 7, 'ref_max_female': 26,
        'optimal_min': 14, 'optimal_max': 25, 'critical_low': 5, 'critical_high': 45,
        'description': 'Iron circulating in blood. Needed for oxygen transport and energy production.',
        'description_bg': 'Желязо, циркулиращо в кръвта. Нужно за транспорт на кислород и производство на енергия.',
        'high_meaning': 'Hemochromatosis (iron overload), liver damage, or excessive supplementation.',
        'high_meaning_bg': 'Хемохроматоза (натрупване на желязо), чернодробно увреждане или прекомерна суплементация.',
        'low_meaning': 'Iron deficiency — most common nutritional deficiency worldwide. Causes fatigue, weakness.',
        'low_meaning_bg': 'Дефицит на желязо — най-честият хранителен дефицит в света. Причинява умора, слабост.',
        'improve_tips': ['Red meat, liver are most bioavailable sources', 'Plant iron: spinach, lentils, fortified cereals', 'Pair with vitamin C (lemon juice on salad)', 'Avoid tea/coffee with iron-rich meals', 'Cook in cast iron pans'],
        'improve_tips_bg': ['Червено месо, черен дроб — най-бионаличните източници', 'Растително желязо: спанак, леща, обогатени зърнени храни', 'Комбинирайте с витамин С (лимонов сок на салата)', 'Избягвайте чай/кафе с храни богати на желязо'],
        'sort_order': 1,
    },
    {
        'category': 'iron_studies', 'abbreviation': 'FERR', 'name': 'Ferritin', 'name_bg': 'Феритин',
        'unit': 'μg/L', 'alt_units': [{'unit': 'ng/mL', 'factor': 1}],
        'aliases': ['Ferritin', 'Феритин', 'FERR'],
        'ref_min_male': 30, 'ref_max_male': 300, 'ref_min_female': 15, 'ref_max_female': 200,
        'optimal_min': 50, 'optimal_max': 150, 'critical_low': 10, 'critical_high': 1000,
        'description': 'Iron storage protein. Best single marker for iron status. Also an inflammation marker.',
        'description_bg': 'Протеин за съхранение на желязо. Най-добрият единичен маркер за статуса на желязото.',
        'high_meaning': 'Iron overload, inflammation, infection, liver disease. Check CRP to distinguish.',
        'high_meaning_bg': 'Натрупване на желязо, възпаление, инфекция, чернодробно заболяване. Проверете CRP за разграничаване.',
        'low_meaning': 'Iron deficiency — even before anemia develops. Hair loss, fatigue, restless legs.',
        'low_meaning_bg': 'Дефицит на желязо — дори преди развитие на анемия. Косопад, умора, неспокойни крака.',
        'improve_tips': ['Same as serum iron tips', 'Ferritin < 30 = iron deficiency even if in "normal" range', 'Consider iron bisglycinate supplement — gentler on stomach', 'Retest after 3 months of supplementation'],
        'improve_tips_bg': ['Същите съвети като за серумно желязо', 'Феритин < 30 = дефицит на желязо дори ако е в "нормалния" диапазон', 'Помислете за добавка на желязо бисглицинат — по-щадящ стомаха'],
        'sort_order': 2,
    },

    # ── INFLAMMATION ─────────────────────────────────────────────────
    {
        'category': 'inflammation', 'abbreviation': 'CRP', 'name': 'C-Reactive Protein', 'name_bg': 'С-реактивен протеин',
        'unit': 'mg/L', 'alt_units': [],
        'aliases': ['CRP', 'C-reactive protein', 'С-реактивен протеин', 'СРП', 'hs-CRP', 'hsCRP'],
        'ref_min_male': 0, 'ref_max_male': 5, 'ref_min_female': 0, 'ref_max_female': 5,
        'optimal_min': 0, 'optimal_max': 1.0, 'critical_low': None, 'critical_high': 100,
        'description': 'General inflammation marker. Low-grade elevation linked to cardiovascular disease risk.',
        'description_bg': 'Общ маркер за възпаление. Нискостепенно повишение свързано с риск от сърдечно-съдови заболявания.',
        'high_meaning': 'Active infection/inflammation (>10), chronic low-grade inflammation (1-10), cardiovascular risk.',
        'high_meaning_bg': 'Активна инфекция/възпаление (>10), хронично нискостепенно възпаление (1-10), сърдечно-съдов риск.',
        'low_meaning': 'Excellent — low inflammation. Keep it up.',
        'low_meaning_bg': 'Отлично — ниско възпаление. Продължавайте така.',
        'improve_tips': ['Anti-inflammatory diet: omega-3, turmeric, ginger, berries', 'Exercise regularly (but avoid overtraining)', 'Sleep 7-9 hours', 'Manage stress', 'Lose visceral fat', 'Limit sugar and processed foods'],
        'improve_tips_bg': ['Противовъзпалителна диета: омега-3, куркума, джинджифил, горски плодове', 'Редовни упражнения (но избягвайте претрениране)', 'Спете 7-9 часа', 'Управлявайте стреса', 'Свалете висцералните мазнини'],
        'sort_order': 1,
    },
    {
        'category': 'inflammation', 'abbreviation': 'ESR', 'name': 'ESR (Sed Rate)', 'name_bg': 'СУЕ',
        'unit': 'mm/h', 'alt_units': [],
        'aliases': ['ESR', 'СУЕ', 'Sed rate', 'Erythrocyte sedimentation rate', 'Скорост на утаяване'],
        'ref_min_male': 0, 'ref_max_male': 15, 'ref_min_female': 0, 'ref_max_female': 20,
        'optimal_min': 0, 'optimal_max': 10, 'critical_low': None, 'critical_high': 100,
        'description': 'Non-specific inflammation marker. Measures how fast red blood cells settle in a tube.',
        'description_bg': 'Неспецифичен маркер за възпаление. Измерва колко бързо червените кръвни клетки се утаяват в епруветка.',
        'high_meaning': 'Infection, inflammation, autoimmune disease, or cancer. Non-specific — needs context.',
        'high_meaning_bg': 'Инфекция, възпаление, автоимунно заболяване или рак. Неспецифично — нужен контекст.',
        'low_meaning': 'Normal — no active inflammation.',
        'low_meaning_bg': 'Нормално — няма активно възпаление.',
        'improve_tips': ['Address underlying cause', 'Anti-inflammatory lifestyle (same as CRP tips)', 'Retest after illness resolves'],
        'improve_tips_bg': ['Адресирайте основната причина', 'Противовъзпалителен начин на живот', 'Повторете теста след отминаване на заболяването'],
        'sort_order': 2,
    },

    # ── HORMONES ─────────────────────────────────────────────────────
    {
        'category': 'hormones', 'abbreviation': 'TESTO', 'name': 'Testosterone (Total)', 'name_bg': 'Тестостерон (общ)',
        'unit': 'nmol/L', 'alt_units': [{'unit': 'ng/dL', 'factor': 0.0347}],
        'aliases': ['Testosterone', 'Тестостерон', 'TESTO', 'Total testosterone', 'Общ тестостерон'],
        'ref_min_male': 8.6, 'ref_max_male': 29, 'ref_min_female': 0.3, 'ref_max_female': 1.7,
        'optimal_min': 15, 'optimal_max': 25, 'critical_low': 5, 'critical_high': None,
        'description': 'Primary male sex hormone. Affects muscle, bone, mood, libido, and energy in both sexes.',
        'description_bg': 'Основен мъжки полов хормон. Влияе на мускулите, костите, настроението, либидото и енергията.',
        'high_meaning': 'In women: PCOS, adrenal disorder. In men: usually from exogenous testosterone.',
        'high_meaning_bg': 'При жени: PCOS, надбъбречно разстройство. При мъже: обикновено от екзогенен тестостерон.',
        'low_meaning': 'In men: fatigue, low libido, muscle loss, depression, metabolic issues. Increasingly common.',
        'low_meaning_bg': 'При мъже: умора, ниско либидо, загуба на мускули, депресия, метаболитни проблеми.',
        'improve_tips': ['Strength training — compound lifts are most effective', 'Sleep 7-9 hours — testosterone produced during deep sleep', 'Maintain healthy body fat (15-20% men)', 'Manage stress — cortisol suppresses testosterone', 'Zinc and vitamin D supplementation', 'Limit alcohol'],
        'improve_tips_bg': ['Силови тренировки — комплексните упражнения са най-ефективни', 'Спете 7-9 часа — тестостеронът се произвежда по време на дълбок сън', 'Поддържайте здравословен процент телесни мазнини', 'Управлявайте стреса', 'Добавки на цинк и витамин D'],
        'sort_order': 1,
    },
    {
        'category': 'hormones', 'abbreviation': 'CORT', 'name': 'Cortisol (Morning)', 'name_bg': 'Кортизол (сутрешен)',
        'unit': 'nmol/L', 'alt_units': [{'unit': 'μg/dL', 'factor': 27.59}],
        'aliases': ['Cortisol', 'Кортизол', 'CORT', 'Morning cortisol', 'Сутрешен кортизол'],
        'ref_min_male': 170, 'ref_max_male': 540, 'ref_min_female': 170, 'ref_max_female': 540,
        'optimal_min': 250, 'optimal_max': 450, 'critical_low': 80, 'critical_high': 700,
        'description': 'Stress hormone produced by adrenal glands. Follows circadian rhythm — highest in morning.',
        'description_bg': 'Стресов хормон, произвеждан от надбъбречните жлези. Следва циркаден ритъм — най-висок сутрин.',
        'high_meaning': 'Chronic stress, Cushing syndrome, sleep deprivation. Causes weight gain, high BP, impaired immunity.',
        'high_meaning_bg': 'Хроничен стрес, синдром на Кушинг, лишаване от сън. Причинява наддаване на тегло, високо кръвно налягане.',
        'low_meaning': 'Adrenal fatigue/insufficiency. Severe fatigue, low blood pressure, dizziness.',
        'low_meaning_bg': 'Надбъбречна умора/недостатъчност. Тежка умора, ниско кръвно налягане, замайване.',
        'improve_tips': ['Stress management: meditation, deep breathing, nature walks', 'Consistent sleep schedule', 'Limit caffeine after 2pm', 'Adaptogenic herbs: ashwagandha, rhodiola', 'Regular moderate exercise (not excessive)'],
        'improve_tips_bg': ['Управление на стреса: медитация, дълбоко дишане, разходки сред природата', 'Последователен график за сън', 'Ограничете кофеина след 14ч', 'Адаптогенни билки: ашваганда, родиола'],
        'sort_order': 2,
    },

    # ── ELECTROLYTES ─────────────────────────────────────────────────
    {
        'category': 'electrolytes', 'abbreviation': 'NA', 'name': 'Sodium', 'name_bg': 'Натрий',
        'unit': 'mmol/L', 'alt_units': [{'unit': 'mEq/L', 'factor': 1}],
        'aliases': ['Sodium', 'Натрий', 'Na', 'NA'],
        'ref_min_male': 136, 'ref_max_male': 145, 'ref_min_female': 136, 'ref_max_female': 145,
        'optimal_min': 138, 'optimal_max': 142, 'critical_low': 125, 'critical_high': 155,
        'description': 'Key electrolyte for fluid balance, nerve function, and blood pressure.',
        'description_bg': 'Ключов електролит за водния баланс, нервната функция и кръвното налягане.',
        'high_meaning': 'Dehydration or excessive salt intake.',
        'high_meaning_bg': 'Дехидратация или прекомерен прием на сол.',
        'low_meaning': 'Overhydration, kidney issues, or hormone imbalance (SIADH). Can cause confusion.',
        'low_meaning_bg': 'Свръххидратация, бъбречни проблеми или хормонален дисбаланс.',
        'improve_tips': ['Stay hydrated but don\'t overdrink', 'Balance sodium and potassium intake'],
        'improve_tips_bg': ['Пийте достатъчно вода, но не прекалявайте', 'Балансирайте приема на натрий и калий'],
        'sort_order': 1,
    },
    {
        'category': 'electrolytes', 'abbreviation': 'K', 'name': 'Potassium', 'name_bg': 'Калий',
        'unit': 'mmol/L', 'alt_units': [{'unit': 'mEq/L', 'factor': 1}],
        'aliases': ['Potassium', 'Калий', 'K'],
        'ref_min_male': 3.5, 'ref_max_male': 5.1, 'ref_min_female': 3.5, 'ref_max_female': 5.1,
        'optimal_min': 3.8, 'optimal_max': 4.8, 'critical_low': 2.5, 'critical_high': 6.5,
        'description': 'Critical electrolyte for heart rhythm, muscle contraction, and nerve signals.',
        'description_bg': 'Критичен електролит за сърдечния ритъм, мускулната контракция и нервните сигнали.',
        'high_meaning': 'Kidney issues, dehydration, or medication effects. Can cause dangerous heart rhythms.',
        'high_meaning_bg': 'Бъбречни проблеми, дехидратация или ефект на лекарства. Може да причини опасни сърдечни ритми.',
        'low_meaning': 'Muscle weakness, cramps, fatigue. Often from diuretics or poor diet.',
        'low_meaning_bg': 'Мускулна слабост, крампи, умора. Често от диуретици или лоша диета.',
        'improve_tips': ['Eat potassium-rich foods: bananas, potatoes, spinach, avocado', 'Balance with sodium', 'Consult doctor before supplementing — can be dangerous if kidney issues'],
        'improve_tips_bg': ['Яжте храни богати на калий: банани, картофи, спанак, авокадо', 'Балансирайте с натрий', 'Консултирайте се с лекар преди суплементация'],
        'sort_order': 2,
    },
    {
        'category': 'electrolytes', 'abbreviation': 'P', 'name': 'Phosphorus', 'name_bg': 'Фосфор',
        'unit': 'mmol/L', 'alt_units': [{'unit': 'mg/dL', 'factor': 3.097}],
        'aliases': ['Phosphorus', 'Фосфор', 'P', 'Inorganic phosphorus', 'Неорганичен фосфор'],
        'ref_min_male': 0.81, 'ref_max_male': 1.45, 'ref_min_female': 0.81, 'ref_max_female': 1.45,
        'optimal_min': 0.9, 'optimal_max': 1.3, 'critical_low': 0.3, 'critical_high': 3.0,
        'description': 'Essential mineral that works with calcium for strong bones and teeth. Also critical for energy production (ATP) and cell signaling.',
        'description_bg': 'Важен минерал, който работи заедно с калция за здрави кости и зъби. Критичен за производството на енергия (АТФ) и клетъчната сигнализация.',
        'high_meaning': 'Kidney disease (most common), hypoparathyroidism, or excessive vitamin D. Can cause calcium deposits in soft tissues.',
        'high_meaning_bg': 'Бъбречно заболяване (най-честа причина), хипопаратиреоидизъм или излишък на витамин D. Може да причини калциеви отлагания.',
        'low_meaning': 'Malnutrition, alcoholism, vitamin D deficiency, or hyperparathyroidism. Can cause muscle weakness and bone pain.',
        'low_meaning_bg': 'Недохранване, алкохолизъм, дефицит на витамин D или хиперпаратиреоидизъм. Може да причини мускулна слабост и костна болка.',
        'improve_tips': ['Dairy, meat, fish, nuts, and legumes are good sources', 'Balance with calcium intake', 'Limit phosphate additives in processed foods'],
        'improve_tips_bg': ['Млечни продукти, месо, риба, ядки и бобови са добри източници', 'Балансирайте с приема на калций', 'Ограничете фосфатните добавки в преработените храни'],
        'sort_order': 4,
    },
    {
        'category': 'electrolytes', 'abbreviation': 'CA', 'name': 'Calcium', 'name_bg': 'Калций',
        'unit': 'mmol/L', 'alt_units': [{'unit': 'mg/dL', 'factor': 4.008}],
        'aliases': ['Calcium', 'Калций', 'Ca', 'CA'],
        'ref_min_male': 2.15, 'ref_max_male': 2.55, 'ref_min_female': 2.15, 'ref_max_female': 2.55,
        'optimal_min': 2.2, 'optimal_max': 2.5, 'critical_low': 1.8, 'critical_high': 3.0,
        'description': 'Essential for bones, teeth, muscle contraction, nerve function, and blood clotting.',
        'description_bg': 'Важен за костите, зъбите, мускулната контракция, нервната функция и кръвосъсирването.',
        'high_meaning': 'Hyperparathyroidism, cancer, or vitamin D excess. Can cause kidney stones.',
        'high_meaning_bg': 'Хиперпаратиреоидизъм, рак или излишък на витамин D. Може да причини бъбречни камъни.',
        'low_meaning': 'Vitamin D deficiency, parathyroid issues, or malabsorption.',
        'low_meaning_bg': 'Дефицит на витамин D, проблеми с паращитовидната жлеза или малабсорбция.',
        'improve_tips': ['Dairy products, fortified plant milks', 'Ensure adequate vitamin D for calcium absorption', 'Weight-bearing exercise strengthens bones', 'Limit excessive caffeine and sodium'],
        'improve_tips_bg': ['Млечни продукти, обогатени растителни млека', 'Осигурете адекватен витамин D за абсорбция на калций', 'Упражнения с тежести укрепват костите'],
        'sort_order': 3,
    },
]


class Command(BaseCommand):
    help = 'Seed biomarker categories and biomarkers with reference data'

    def handle(self, *args, **options):
        # §SEED: Idempotent — update_or_create keyed on slug/abbreviation
        cat_map = {}
        for cat_data in CATEGORIES:
            obj, created = BiomarkerCategory.objects.update_or_create(
                slug=cat_data['slug'],
                defaults=cat_data,
            )
            cat_map[cat_data['slug']] = obj
            status = 'Created' if created else 'Updated'
            self.stdout.write(f"  {status} category: {obj.name}")

        for bm_data in BIOMARKERS:
            cat = cat_map[bm_data.pop('category')]
            abbr = bm_data['abbreviation']
            obj, created = Biomarker.objects.update_or_create(
                abbreviation=abbr,
                defaults={**bm_data, 'category': cat},
            )
            status = 'Created' if created else 'Updated'
            self.stdout.write(f"  {status} biomarker: {obj.name} ({abbr})")

        # Set up related biomarkers
        self._link_related()
        self.stdout.write(self.style.SUCCESS(
            f'\nSeeded {BiomarkerCategory.objects.count()} categories, '
            f'{Biomarker.objects.count()} biomarkers.'
        ))

    def _link_related(self):
        """§REL: Link related biomarkers for cross-correlation display."""
        relations = [
            # Iron study triangle
            (['FE', 'FERR', 'HGB'],),
            # Lipid panel interconnection
            (['CHOL', 'LDL', 'HDL', 'TG', 'VLDL'],),
            # Liver enzymes + protein
            (['ALT', 'AST', 'GGT', 'TBIL', 'ALP', 'DBIL'],),
            # Kidney pair
            (['CREA', 'UREA', 'URIC'],),
            # Thyroid axis
            (['TSH', 'FT4'],),
            # Metabolic
            (['GLU', 'HBA1C'],),
            # Blood cells — core
            (['HGB', 'RBC', 'HCT', 'MCV', 'MCH', 'MCHC'],),
            # Red cell indices
            (['MCV', 'MCH', 'MCHC', 'RDW'],),
            # Protein panel
            (['TP', 'ALB'],),
            # Iron + CBC anemia markers
            (['FE', 'FERR', 'MCV', 'MCH', 'RDW'],),
        ]
        for group in relations:
            abbrs = group[0]
            markers = list(Biomarker.objects.filter(abbreviation__in=abbrs))
            for m in markers:
                m.related_biomarkers.set([r for r in markers if r.id != m.id])
