# Generated by Django 6.0.2 on 2026-02-27 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("insurance", "Insurance"),
                            ("mortgage", "Mortgage"),
                            ("lease", "Lease"),
                            ("tax", "Tax"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "reminder_30_days",
                    models.BooleanField(
                        default=False, help_text="Has 30-day reminder been sent?"
                    ),
                ),
                (
                    "reminder_5_days",
                    models.BooleanField(
                        default=False, help_text="Has 5-day reminder been sent?"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="properties.property",
                    ),
                ),
            ],
        ),
    ]
