# Generated by Django 6.0.2 on 2026-03-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("insurance", "Insurance"),
                    ("mortgage", "Mortgage"),
                    ("lease", "Lease"),
                    ("tax", "Tax"),
                    ("utility", "Utility"),
                    ("maintenance", "Maintenance"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
