# Generated by Django 6.0.2 on 2026-03-06 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_document_document_type"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AddField(
            model_name="document",
            name="file_size",
            field=models.PositiveIntegerField(
                default=0, help_text="File size in bytes"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional display name (auto-derived from filename if blank)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="replaces",
            field=models.ForeignKey(
                blank=True,
                help_text="Previous version of this document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaced_by",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("insurance", "Insurance"),
                    ("mortgage", "Mortgage"),
                    ("lease", "Lease Agreement"),
                    ("tax", "Tax"),
                    ("utility_electricity", "Electricity"),
                    ("utility_water", "Water"),
                    ("utility_gas", "Gas"),
                    ("utility_heating", "Heating"),
                    ("utility_internet", "Internet"),
                    ("building_mgmt", "Building Management"),
                    ("security", "Security"),
                    ("deed", "Property Deed"),
                    ("notary", "Notary Act"),
                    ("valuation", "Valuation Report"),
                    ("inspection", "Inspection Report"),
                    ("maintenance", "Maintenance"),
                    ("receipt", "Receipt"),
                    ("photo", "Photo"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["property", "document_type"],
                name="documents_d_propert_a1fe99_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["expiry_date"], name="documents_d_expiry__1d702a_idx"
            ),
        ),
    ]
