# Generated by Django 6.0.2 on 2026-03-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0002_initial"),
        ("properties", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="auto_generate_payments",
            field=models.BooleanField(
                default=True,
                help_text="Auto-create RentPayment records for recurring leases",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="next_payment_date",
            field=models.DateField(
                blank=True,
                help_text="Next date a payment record will be generated for",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="rent_frequency",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Bi-weekly"),
                    ("one_time", "One-time / Airbnb"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="monthly_rent",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Rent amount per period (monthly/weekly/biweekly/one-time)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="lease",
            name="rent_due_day",
            field=models.IntegerField(
                default=1,
                help_text="Day of month rent is due (1-28) for monthly leases",
            ),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["status", "auto_generate_payments"],
                name="leases_leas_status_4251f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["next_payment_date"], name="leases_leas_next_pa_48fdb7_idx"
            ),
        ),
    ]
