# Generated by Django 6.0.2 on 2026-03-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "leases",
            "0003_lease_auto_generate_payments_lease_next_payment_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="electricity_meter_in",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Electricity meter reading at move-in",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="electricity_meter_out",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Electricity meter reading at move-out",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="gas_meter_in",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Gas meter reading at move-in",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="gas_meter_out",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Gas meter reading at move-out",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="water_meter_in",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Water meter reading at move-in",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="water_meter_out",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Water meter reading at move-out",
                max_digits=12,
                null=True,
            ),
        ),
    ]
