# Generated by Django 6.0.2 on 2026-03-06 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0004_lease_electricity_meter_in_and_more"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional — which unit within the property this lease is for",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leases",
                to="properties.unit",
            ),
        ),
    ]
