# Generated by Django 6.0.2 on 2026-04-10 14:31

from django.db import migrations


def enable_weekly_payments(apps, schema_editor):
    """Enable auto_generate_payments for all weekly leases and generate missing payments."""
    Lease = apps.get_model('leases', 'Lease')
    RentPayment = apps.get_model('finance', 'RentPayment')

    from datetime import date, timedelta
    from dateutil.relativedelta import relativedelta

    # Find all active weekly leases
    weekly_leases = Lease.objects.filter(
        rent_frequency='weekly',
        status='active'
    )

    for lease in weekly_leases:
        # Enable auto-generation
        lease.auto_generate_payments = True

        # Initialize cursor if not set
        if lease.next_payment_date is None:
            lease.next_payment_date = lease.start_date

        lease.save()

        # Generate payments up to 4 weeks ahead
        today = date.today()
        look_ahead = today + timedelta(weeks=4)
        end_limit = min(look_ahead, lease.end_date)

        cursor = lease.next_payment_date
        while cursor <= end_limit:
            # Check if payment exists
            exists = RentPayment.objects.filter(
                lease=lease, due_date=cursor
            ).exists()

            if not exists:
                RentPayment.objects.create(
                    lease=lease,
                    due_date=cursor,
                    amount_due=lease.monthly_rent,
                    amount_paid=0,
                    status='pending',
                )

            # Advance to next week
            cursor += timedelta(weeks=1)

        # Update cursor
        lease.next_payment_date = cursor
        lease.save()


def reverse_weekly_payments(apps, schema_editor):
    """Reverse: disable auto-generation (doesn't delete payments)."""
    Lease = apps.get_model('leases', 'Lease')
    Lease.objects.filter(rent_frequency='weekly').update(auto_generate_payments=False)


class Migration(migrations.Migration):

    dependencies = [
        ("leases", "0005_lease_unit"),
    ]

    operations = [
        migrations.RunPython(enable_weekly_payments, reverse_weekly_payments),
    ]
