# Generated by Django 6.0.2 on 2026-04-02 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leases", "0005_lease_unit"),
        ("problems", "0001_initial"),
        ("properties", "0002_add_parent_property_and_types"),
        ("tenants", "0002_simplify_tenant_to_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("gray", "Gray"),
                            ("red", "Red"),
                            ("orange", "Orange"),
                            ("yellow", "Yellow"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("indigo", "Indigo"),
                            ("purple", "Purple"),
                        ],
                        default="gray",
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                ("position", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="notes.notefolder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="NoteTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("gray", "Gray"),
                            ("red", "Red"),
                            ("orange", "Orange"),
                            ("yellow", "Yellow"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("indigo", "Indigo"),
                            ("purple", "Purple"),
                        ],
                        default="gray",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("content", models.JSONField(blank=True, default=list)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("yellow", "Yellow"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("purple", "Purple"),
                            ("pink", "Pink"),
                        ],
                        default="white",
                        max_length=20,
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_trashed", models.BooleanField(default=False)),
                ("trashed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "checklist_stats",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"total": 0, "checked": 0} — computed from content blocks',
                    ),
                ),
                ("word_count", models.IntegerField(default=0)),
                ("is_template", models.BooleanField(default=False)),
                (
                    "template_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_lease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_notes",
                        to="leases.lease",
                    ),
                ),
                (
                    "linked_problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_notes",
                        to="problems.problem",
                    ),
                ),
                (
                    "linked_property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_notes",
                        to="properties.property",
                    ),
                ),
                (
                    "linked_tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_notes",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes",
                        to="notes.notefolder",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="notes", to="notes.notetag"
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notefolder",
            index=models.Index(
                fields=["user", "position"], name="notes_notef_user_id_9a0c6e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notetag",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["user", "-updated_at"], name="notes_note_user_id_d67ab6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["user", "is_trashed", "-updated_at"],
                name="notes_note_user_id_213ec5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["user", "folder", "-updated_at"],
                name="notes_note_user_id_cdce82_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["user", "is_pinned", "-updated_at"],
                name="notes_note_user_id_1884e8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["linked_property"], name="notes_note_linked__d11446_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["linked_tenant"], name="notes_note_linked__aba52f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["linked_lease"], name="notes_note_linked__46c73a_idx"
            ),
        ),
    ]
