# Generated by Django 6.0.2 on 2026-04-11 10:23

from django.db import migrations, models


def set_existing_notes_to_blocks(apps, schema_editor):
    """Set all existing notes to 'blocks' for backward compatibility."""
    Note = apps.get_model('notes', 'Note')
    Note.objects.all().update(content_type='blocks')


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("blocks", "Block-based"),
                    ("richtext", "Rich text"),
                    ("plaintext", "Plain text"),
                ],
                default="richtext",
                help_text="Content format: blocks (legacy), richtext (HTML with toolbar), or plaintext (unformatted)",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_existing_notes_to_blocks),
    ]
