# Generated by Django 6.0.2 on 2026-04-02 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiomarkerCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_bg", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("icon", models.CharField(blank=True, default="", max_length=10)),
                (
                    "body_system",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Biomarker categories",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Biomarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_bg", models.CharField(blank=True, default="", max_length=200)),
                (
                    "abbreviation",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("unit", models.CharField(max_length=50)),
                ("alt_units", models.JSONField(blank=True, default=list)),
                ("ref_min_male", models.FloatField(blank=True, null=True)),
                ("ref_max_male", models.FloatField(blank=True, null=True)),
                ("ref_min_female", models.FloatField(blank=True, null=True)),
                ("ref_max_female", models.FloatField(blank=True, null=True)),
                ("optimal_min", models.FloatField(blank=True, null=True)),
                ("optimal_max", models.FloatField(blank=True, null=True)),
                ("critical_low", models.FloatField(blank=True, null=True)),
                ("critical_high", models.FloatField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("description_bg", models.TextField(blank=True, default="")),
                ("high_meaning", models.TextField(blank=True, default="")),
                ("high_meaning_bg", models.TextField(blank=True, default="")),
                ("low_meaning", models.TextField(blank=True, default="")),
                ("low_meaning_bg", models.TextField(blank=True, default="")),
                ("improve_tips", models.JSONField(blank=True, default=list)),
                ("improve_tips_bg", models.JSONField(blank=True, default=list)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "related_biomarkers",
                    models.ManyToManyField(blank=True, to="health.biomarker"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biomarkers",
                        to="health.biomarkercategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category__sort_order", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="HealthProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=10,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="BloodReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_date", models.DateField()),
                ("lab_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "lab_type",
                    models.CharField(
                        choices=[
                            ("ramus", "Ramus"),
                            ("lina", "LINA"),
                            ("acibadem", "Acibadem"),
                            ("cibalab", "Cibalab"),
                            ("other", "Other"),
                            ("manual", "Manual Entry"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="health/reports/%Y/%m/"
                    ),
                ),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("overall_score", models.IntegerField(blank=True, null=True)),
                ("system_scores", models.JSONField(blank=True, default=dict)),
                ("parsed_raw", models.JSONField(blank=True, default=dict)),
                ("parse_warnings", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="health.healthprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-test_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("diet", "Diet"),
                            ("exercise", "Exercise"),
                            ("supplement", "Supplement"),
                            ("medical", "Medical"),
                            ("lifestyle", "Lifestyle"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_bg", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.TextField()),
                ("description_bg", models.TextField(blank=True, default="")),
                ("related_biomarkers", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="health.bloodreport",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "category"],
            },
        ),
        migrations.CreateModel(
            name="BloodResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
                (
                    "flag",
                    models.CharField(
                        choices=[
                            ("optimal", "Optimal"),
                            ("normal", "Normal"),
                            ("borderline_high", "Borderline High"),
                            ("borderline_low", "Borderline Low"),
                            ("high", "High"),
                            ("low", "Low"),
                            ("critical_high", "Critical High"),
                            ("critical_low", "Critical Low"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("deviation_pct", models.FloatField(blank=True, null=True)),
                (
                    "ref_range_text",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "biomarker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="health.biomarker",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="health.bloodreport",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "biomarker__category__sort_order",
                    "biomarker__sort_order",
                ],
                "indexes": [
                    models.Index(
                        fields=["biomarker", "report"],
                        name="health_bloo_biomark_a4af06_idx",
                    )
                ],
                "unique_together": {("report", "biomarker")},
            },
        ),
        migrations.AddIndex(
            model_name="bloodreport",
            index=models.Index(
                fields=["user", "profile", "-test_date"],
                name="health_bloo_user_id_89c3ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bloodreport",
            index=models.Index(
                fields=["user", "-test_date"], name="health_bloo_user_id_24d651_idx"
            ),
        ),
    ]
