# Generated by Django 6.0.2 on 2026-04-04 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BPMedication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("dose", models.CharField(max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("twice_daily", "Twice Daily"),
                            ("as_needed", "As Needed"),
                            ("other", "Other"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateField()),
                ("ended_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bp_medications",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bp_medications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "-started_at"],
            },
        ),
        migrations.CreateModel(
            name="BPSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measured_at", models.DateTimeField()),
                ("avg_systolic", models.FloatField(blank=True, null=True)),
                ("avg_diastolic", models.FloatField(blank=True, null=True)),
                ("avg_pulse", models.FloatField(blank=True, null=True)),
                ("reading_count", models.IntegerField(default=0)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("elevated", "Elevated"),
                            ("stage_1", "Hypertension Stage 1"),
                            ("stage_2", "Hypertension Stage 2"),
                            ("crisis", "Hypertensive Crisis"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bp_sessions",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bp_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-measured_at"],
            },
        ),
        migrations.CreateModel(
            name="BPReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("systolic", models.IntegerField()),
                ("diastolic", models.IntegerField()),
                ("pulse", models.IntegerField(blank=True, null=True)),
                ("measured_at", models.DateTimeField()),
                (
                    "arm",
                    models.CharField(
                        choices=[("left", "Left"), ("right", "Right")],
                        default="left",
                        max_length=10,
                    ),
                ),
                (
                    "posture",
                    models.CharField(
                        choices=[
                            ("sitting", "Sitting"),
                            ("standing", "Standing"),
                            ("lying", "Lying"),
                        ],
                        default="sitting",
                        max_length=10,
                    ),
                ),
                ("is_after_caffeine", models.BooleanField(default=False)),
                ("is_after_exercise", models.BooleanField(default=False)),
                ("is_after_medication", models.BooleanField(default=False)),
                ("is_stressed", models.BooleanField(default=False)),
                ("is_clinic_reading", models.BooleanField(default=False)),
                ("is_fasting", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bp_readings",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bp_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="readings",
                        to="health.bpsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-measured_at"],
            },
        ),
        migrations.CreateModel(
            name="BPMedLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("taken", models.BooleanField(default=False)),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="health.bpmedication",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("medication", "date")},
            },
        ),
        migrations.CreateModel(
            name="BPAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("crisis", "Hypertensive Crisis"),
                            ("sustained_high", "Sustained High BP"),
                            ("stage_change", "Stage Change"),
                            ("morning_surge", "Morning Surge"),
                            ("white_coat", "White Coat Hypertension"),
                            ("masked_hypertension", "Masked Hypertension"),
                            ("high_variability", "High Variability"),
                            ("medication_effective", "Medication Effective"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_bg", models.CharField(blank=True, default="", max_length=200)),
                ("message", models.TextField()),
                ("message_bg", models.TextField(blank=True, default="")),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bp_alerts",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bp_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_reading",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="health.bpreading",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "profile", "-created_at"],
                        name="health_bpal_user_id_6cee5c_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="health_bpal_user_id_6950cb_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="bpsession",
            index=models.Index(
                fields=["user", "profile", "-measured_at"],
                name="health_bpse_user_id_974bee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bpreading",
            index=models.Index(
                fields=["user", "profile", "-measured_at"],
                name="health_bpre_user_id_d14872_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bpreading",
            index=models.Index(
                fields=["session"], name="health_bpre_session_3dafbf_idx"
            ),
        ),
    ]
