# Generated by Django 6.0.2 on 2026-04-04 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_bp_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhoopConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whoop_user_id", models.BigIntegerField(blank=True, null=True)),
                ("access_token", models.TextField(default="")),
                ("refresh_token", models.TextField(default="")),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("scopes", models.TextField(blank=True, default="")),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sync_error", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whoop_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-connected_at"],
            },
        ),
        migrations.CreateModel(
            name="WhoopCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whoop_id", models.BigIntegerField(unique=True)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("timezone_offset", models.CharField(default="+00:00", max_length=10)),
                (
                    "score_state",
                    models.CharField(
                        choices=[
                            ("scored", "Scored"),
                            ("pending", "Pending"),
                            ("unscorable", "Unscorable"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("strain", models.FloatField(blank=True, null=True)),
                ("kilojoule", models.FloatField(blank=True, null=True)),
                ("average_heart_rate", models.IntegerField(blank=True, null=True)),
                ("max_heart_rate", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whoop_cycles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start"],
            },
        ),
        migrations.CreateModel(
            name="WhoopRecovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sleep_id", models.CharField(blank=True, default="", max_length=100)),
                (
                    "score_state",
                    models.CharField(
                        choices=[
                            ("scored", "Scored"),
                            ("pending", "Pending"),
                            ("unscorable", "Unscorable"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("recovery_score", models.IntegerField(blank=True, null=True)),
                ("resting_heart_rate", models.IntegerField(blank=True, null=True)),
                ("hrv_rmssd_milli", models.FloatField(blank=True, null=True)),
                ("spo2_percentage", models.FloatField(blank=True, null=True)),
                ("skin_temp_celsius", models.FloatField(blank=True, null=True)),
                ("user_calibrating", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cycle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery",
                        to="health.whoopcycle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whoop_recoveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "whoop recoveries",
                "ordering": ["-cycle__start"],
            },
        ),
        migrations.CreateModel(
            name="WhoopSleep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whoop_id", models.CharField(max_length=100, unique=True)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("timezone_offset", models.CharField(default="+00:00", max_length=10)),
                ("nap", models.BooleanField(default=False)),
                (
                    "score_state",
                    models.CharField(
                        choices=[
                            ("scored", "Scored"),
                            ("pending", "Pending"),
                            ("unscorable", "Unscorable"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("sleep_performance_pct", models.IntegerField(blank=True, null=True)),
                ("sleep_consistency_pct", models.IntegerField(blank=True, null=True)),
                ("sleep_efficiency_pct", models.FloatField(blank=True, null=True)),
                ("respiratory_rate", models.FloatField(blank=True, null=True)),
                ("total_in_bed_milli", models.BigIntegerField(blank=True, null=True)),
                ("total_awake_milli", models.BigIntegerField(blank=True, null=True)),
                ("total_light_milli", models.BigIntegerField(blank=True, null=True)),
                ("total_sws_milli", models.BigIntegerField(blank=True, null=True)),
                ("total_rem_milli", models.BigIntegerField(blank=True, null=True)),
                ("sleep_cycle_count", models.IntegerField(blank=True, null=True)),
                ("disturbance_count", models.IntegerField(blank=True, null=True)),
                (
                    "sleep_needed_baseline_milli",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "sleep_needed_debt_milli",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "sleep_needed_strain_milli",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "sleep_needed_nap_milli",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sleeps",
                        to="health.whoopcycle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whoop_sleeps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start"],
            },
        ),
        migrations.CreateModel(
            name="WhoopWorkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whoop_id", models.CharField(max_length=100, unique=True)),
                ("sport_id", models.IntegerField(default=0)),
                ("sport_name", models.CharField(default="", max_length=100)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("timezone_offset", models.CharField(default="+00:00", max_length=10)),
                (
                    "score_state",
                    models.CharField(
                        choices=[
                            ("scored", "Scored"),
                            ("pending", "Pending"),
                            ("unscorable", "Unscorable"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("strain", models.FloatField(blank=True, null=True)),
                ("average_heart_rate", models.IntegerField(blank=True, null=True)),
                ("max_heart_rate", models.IntegerField(blank=True, null=True)),
                ("kilojoule", models.FloatField(blank=True, null=True)),
                ("percent_recorded", models.IntegerField(blank=True, null=True)),
                ("distance_meter", models.FloatField(blank=True, null=True)),
                ("altitude_gain_meter", models.FloatField(blank=True, null=True)),
                ("zone_zero_milli", models.BigIntegerField(blank=True, null=True)),
                ("zone_one_milli", models.BigIntegerField(blank=True, null=True)),
                ("zone_two_milli", models.BigIntegerField(blank=True, null=True)),
                ("zone_three_milli", models.BigIntegerField(blank=True, null=True)),
                ("zone_four_milli", models.BigIntegerField(blank=True, null=True)),
                ("zone_five_milli", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workouts",
                        to="health.whoopcycle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whoop_workouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start"],
            },
        ),
        migrations.AddIndex(
            model_name="whoopcycle",
            index=models.Index(
                fields=["user", "-start"], name="health_whoo_user_id_74c142_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whooprecovery",
            index=models.Index(
                fields=["user", "-created_at"], name="health_whoo_user_id_461c08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whoopsleep",
            index=models.Index(
                fields=["user", "-start"], name="health_whoo_user_id_92c8fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whoopworkout",
            index=models.Index(
                fields=["user", "-start"], name="health_whoo_user_id_5791c2_idx"
            ),
        ),
    ]
