# Generated by Django 6.0.2 on 2026-04-04 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0003_whoop_integration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthScoreSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("composite_score", models.IntegerField(blank=True, null=True)),
                ("blood_score", models.IntegerField(blank=True, null=True)),
                ("bp_score", models.IntegerField(blank=True, null=True)),
                ("recovery_score", models.IntegerField(blank=True, null=True)),
                ("lifestyle_score", models.IntegerField(blank=True, null=True)),
                ("confidence", models.FloatField(default=0.0)),
                ("inputs", models.JSONField(blank=True, default=dict)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "profile", "-date"],
                        name="health_heal_user_id_e92405_idx",
                    )
                ],
                "unique_together": {("user", "profile", "date")},
            },
        ),
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("supplement", "Supplement"),
                            ("medication", "Medication"),
                            ("diet", "Diet"),
                            ("exercise", "Exercise"),
                            ("sleep", "Sleep"),
                            ("habit", "Habit"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dose", models.CharField(blank=True, default="", max_length=100)),
                ("started_on", models.DateField()),
                ("ended_on", models.DateField(blank=True, null=True)),
                ("hypothesis", models.TextField(blank=True, default="")),
                ("target_metrics", models.JSONField(blank=True, default=list)),
                (
                    "evidence_grade",
                    models.CharField(
                        choices=[
                            ("A", "A — Strong (RCTs / meta-analysis)"),
                            (
                                "B",
                                "B — Moderate (small trials / consistent observational)",
                            ),
                            (
                                "C",
                                "C — Preliminary (animal / mechanistic / early human)",
                            ),
                            ("anecdote", "Anecdote / self-experiment"),
                        ],
                        default="B",
                        max_length=10,
                    ),
                ),
                ("source_url", models.URLField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interventions",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_on", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-started_on"],
                        name="health_inte_user_id_b261ab_idx",
                    )
                ],
            },
        ),
    ]
