# Generated by Django 6.0.2 on 2026-04-05 06:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0004_healthscoresnapshot_intervention"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeightMedicationEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication_name", models.CharField(max_length=120, unique=True)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("drug_class", models.CharField(blank=True, default="", max_length=60)),
                (
                    "avg_weight_delta_kg",
                    models.DecimalField(decimal_places=1, max_digits=3),
                ),
                ("onset_weeks", models.SmallIntegerField(default=8)),
                (
                    "evidence_level",
                    models.CharField(
                        choices=[
                            ("strong", "Strong"),
                            ("moderate", "Moderate"),
                            ("anecdotal", "Anecdotal"),
                        ],
                        default="moderate",
                        max_length=10,
                    ),
                ),
                ("mechanism", models.TextField(blank=True, default="")),
                ("mechanism_bg", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["medication_name"],
            },
        ),
        migrations.AddField(
            model_name="healthprofile",
            name="height_cm",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.CreateModel(
            name="VitalsSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ritual_type",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("evening", "Evening"),
                            ("pre_meal", "Pre-Meal"),
                            ("doctor_visit", "Doctor Visit"),
                            ("custom", "Custom"),
                        ],
                        default="morning",
                        max_length=20,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("weight_captured", models.BooleanField(default=False)),
                ("bp_reading_count", models.SmallIntegerField(default=0)),
                ("cached_summary", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals_sessions",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="WeightGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("lose", "Lose"),
                            ("gain", "Gain"),
                            ("maintain", "Maintain"),
                            ("bp_driven", "BP-Driven"),
                        ],
                        default="lose",
                        max_length=20,
                    ),
                ),
                (
                    "start_weight_kg",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "target_weight_kg",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("weekly_rate_kg", models.DecimalField(decimal_places=2, max_digits=4)),
                ("started_at", models.DateField()),
                ("target_date", models.DateField()),
                ("achieved_at", models.DateField(blank=True, null=True)),
                ("linked_bp_target", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_goals",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeightReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measured_at", models.DateTimeField()),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("20")),
                            django.core.validators.MaxValueValidator(Decimal("400")),
                        ],
                    ),
                ),
                (
                    "body_fat_pct",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "muscle_mass_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "body_water_pct",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "visceral_fat_rating",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "bone_mass_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "waist_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "hip_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("context_flags", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("csv", "CSV Import"),
                            ("withings", "Withings"),
                            ("apple_health", "Apple Health"),
                            ("garmin", "Garmin"),
                            ("renpho", "Renpho"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_readings",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weight_readings",
                        to="health.vitalssession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-measured_at"],
            },
        ),
        migrations.CreateModel(
            name="VitalsInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("bp_per_kg_slope", "BP per kg Slope"),
                            ("cardiometabolic_age", "Cardiometabolic Age"),
                            ("osmotic_spike", "Osmotic Spike"),
                            ("stage_regression_forecast", "Stage Regression Forecast"),
                            ("goal_progress", "Goal Progress"),
                            ("plateau", "Plateau"),
                            ("whoosh", "Whoosh"),
                            ("med_attribution", "Medication Attribution"),
                            ("trend_break", "Trend Break"),
                            ("smart_sampling", "Smart Sampling"),
                        ],
                        max_length=40,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("window_start", models.DateField(blank=True, null=True)),
                ("window_end", models.DateField(blank=True, null=True)),
                ("payload", models.JSONField()),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.50"), max_digits=3
                    ),
                ),
                ("algo_version", models.CharField(default="v1", max_length=10)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals_insights",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="health.vitalsinsight",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-computed_at"],
                "indexes": [
                    models.Index(
                        fields=["profile", "insight_type", "-computed_at"],
                        name="health_vita_profile_e3e2e9_idx",
                    ),
                    models.Index(
                        fields=["profile", "-computed_at"],
                        name="health_vita_profile_d751b8_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="vitalssession",
            index=models.Index(
                fields=["profile", "-started_at"], name="health_vita_profile_142958_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weightgoal",
            index=models.Index(
                fields=["profile", "is_active"], name="health_weig_profile_15a402_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weightreading",
            index=models.Index(
                fields=["profile", "-measured_at"],
                name="health_weig_profile_e1d7f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="weightreading",
            index=models.Index(
                fields=["user", "-measured_at"], name="health_weig_user_id_76f777_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="weightreading",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_ref__gt", "")),
                fields=("user", "source", "source_ref"),
                name="uniq_weight_source_ref",
            ),
        ),
    ]
