# Generated by Django 6.0.2 on 2026-04-05 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0005_weightmedicationeffect_healthprofile_height_cm_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterventionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("taken", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="health.intervention",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["intervention", "-date"],
                        name="health_inte_interve_39791f_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("intervention", "date"),
                        name="uniq_intervention_log_per_day",
                    )
                ],
            },
        ),
    ]
