# Generated by Django 6.0.2 on 2026-04-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0006_interventionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Once daily"),
                    ("twice_daily", "Twice daily"),
                    ("three_daily", "Three times daily"),
                    ("weekly", "Weekly"),
                    ("as_needed", "As needed"),
                    ("one_time", "One-time"),
                ],
                default="daily",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="reminder_times",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
