# Generated by Django 6.0.2 on 2026-04-06 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0007_intervention_frequency_reminders"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoutAttack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("onset_date", models.DateField(help_text="When the attack started")),
                (
                    "resolved_date",
                    models.DateField(
                        blank=True, help_text="When it resolved", null=True
                    ),
                ),
                (
                    "joint",
                    models.CharField(
                        choices=[
                            ("big_toe", "Big Toe"),
                            ("ankle", "Ankle"),
                            ("knee", "Knee"),
                            ("wrist", "Wrist"),
                            ("finger", "Finger"),
                            ("elbow", "Elbow"),
                            ("heel", "Heel / Foot"),
                            ("other", "Other"),
                        ],
                        default="big_toe",
                        max_length=20,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("right", "Right"),
                            ("both", "Both"),
                        ],
                        default="right",
                        max_length=10,
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(default=5, help_text="Pain severity 1-10"),
                ),
                ("swelling", models.BooleanField(default=True)),
                ("redness", models.BooleanField(default=False)),
                ("warmth", models.BooleanField(default=False)),
                (
                    "medication",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("colchicine", "Colchicine"),
                            ("allopurinol", "Allopurinol"),
                            ("febuxostat", "Febuxostat"),
                            ("nsaid", "NSAID (Ibuprofen, Naproxen)"),
                            ("prednisone", "Prednisone"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "medication_dose",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g. "2 on day 1, 1 on day 2"',
                        max_length=100,
                    ),
                ),
                (
                    "uric_acid_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Uric acid level in µmol/L at time of attack",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "day_before_food",
                    models.TextField(
                        blank=True, default="", help_text="What was eaten 24-48h before"
                    ),
                ),
                (
                    "day_before_activity",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Physical activity before the attack",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gout_attacks",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gout_attacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-onset_date"],
            },
        ),
        migrations.CreateModel(
            name="AttackTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("drink", "Drink"),
                            ("activity", "Physical Activity"),
                            ("stress", "Stress"),
                            ("weather", "Weather"),
                            ("medication", "Medication"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g. "beer", "squatting", "processed meat"',
                        max_length=100,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "attack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggers",
                        to="health.goutattack",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="MedicalProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("procedure_date", models.DateField()),
                (
                    "procedure_type",
                    models.CharField(
                        choices=[
                            ("fluid_drainage", "Fluid Drainage (Aspiration)"),
                            ("injection", "Corticosteroid Injection"),
                            ("blood_test", "Blood Test"),
                            ("xray", "X-Ray"),
                            ("ultrasound", "Ultrasound"),
                            ("mri", "MRI"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "joint",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("big_toe", "Big Toe"),
                            ("ankle", "Ankle"),
                            ("knee", "Knee"),
                            ("wrist", "Wrist"),
                            ("finger", "Finger"),
                            ("elbow", "Elbow"),
                            ("heel", "Heel / Foot"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("left", "Left"),
                            ("right", "Right"),
                            ("both", "Both"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("doctor", models.CharField(blank=True, default="", max_length=200)),
                (
                    "findings",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Results/findings from the procedure",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gout_procedures",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gout_procedures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-procedure_date"],
            },
        ),
        migrations.CreateModel(
            name="UricAcidReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measured_at", models.DateField()),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Uric acid in µmol/L (normal: <360, your target: <300)",
                        max_digits=5,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uric_acid_readings",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uric_acid_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-measured_at"],
            },
        ),
        migrations.AddIndex(
            model_name="goutattack",
            index=models.Index(
                fields=["user", "-onset_date"], name="health_gout_user_id_534a95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goutattack",
            index=models.Index(fields=["joint"], name="health_gout_joint_67c7bb_idx"),
        ),
        migrations.AddIndex(
            model_name="uricacidreading",
            index=models.Index(
                fields=["user", "-measured_at"], name="health_uric_user_id_ad2a27_idx"
            ),
        ),
    ]
