# Generated by Django 6.0.2 on 2026-04-06 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0008_goutattack_attacktrigger_medicalprocedure_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RitualItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("medication", "Medication"),
                            ("supplement", "Supplement"),
                            ("injection", "Injection"),
                            ("meal", "Meal"),
                            ("exercise", "Exercise"),
                            ("work", "Work"),
                            ("social", "Social / Family"),
                            ("sleep", "Sleep"),
                            ("hydration", "Hydration"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dose",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g. "80mg", "250-500mg", "half tablet"',
                        max_length=100,
                    ),
                ),
                (
                    "instructions",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g. "with food", "fasted", "30min before gym"',
                        max_length=300,
                    ),
                ),
                (
                    "scheduled_time",
                    models.TimeField(
                        blank=True, help_text="Suggested time (HH:MM)", null=True
                    ),
                ),
                (
                    "timing",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("fasted", "Fasted Window"),
                            ("with_meal_1", "With First Meal"),
                            ("pre_workout", "Pre-Workout"),
                            ("with_meal_2", "With Last Meal"),
                            ("evening", "Evening"),
                            ("bedtime", "Bedtime"),
                            ("anytime", "Anytime"),
                        ],
                        default="anytime",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("daily", "Every Day"),
                            ("gym_day", "Gym Days Only"),
                            ("sex_day", "Sex Day Only"),
                            ("gout_flare_pause", "Pause During Gout Flare"),
                            ("as_needed", "As Needed"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "warning",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Interaction or caution note",
                        max_length=500,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Badge color hint",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ritual_items",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ritual_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="RitualLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "skipped",
                    models.BooleanField(
                        default=False,
                        help_text="Intentionally skipped (e.g. gout flare)",
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="health.ritualitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="BodyMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measured_at", models.DateField()),
                (
                    "site",
                    models.CharField(
                        choices=[
                            ("belly_under", "Under Belly (Navel)"),
                            ("belly_mid", "Mid Belly"),
                            ("chest", "Chest (Nipple Line)"),
                            ("bicep_right", "Right Bicep"),
                            ("bicep_left", "Left Bicep"),
                            ("waist", "Waist"),
                            ("hips", "Hips"),
                            ("thigh_right", "Right Thigh"),
                            ("thigh_left", "Left Thigh"),
                            ("neck", "Neck"),
                            ("forearm_right", "Right Forearm"),
                            ("forearm_left", "Left Forearm"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value_cm",
                    models.DecimalField(
                        decimal_places=1, help_text="Measurement in cm", max_digits=5
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_measurements",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_measurements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-measured_at", "site"],
                "indexes": [
                    models.Index(
                        fields=["user", "-measured_at"],
                        name="health_body_user_id_1178de_idx",
                    )
                ],
                "unique_together": {("user", "measured_at", "site")},
            },
        ),
        migrations.AddIndex(
            model_name="ritualitem",
            index=models.Index(
                fields=["user", "is_active"], name="health_ritu_user_id_2df1fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rituallog",
            index=models.Index(
                fields=["date", "completed"], name="health_ritu_date_8f6c9e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rituallog",
            unique_together={("item", "date")},
        ),
    ]
