# Generated by Django 6.0.2 on 2026-04-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0009_ritualitem_rituallog_bodymeasurement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ritualitem",
            name="prescription_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Doctor name, clinic, prescription details for pharmacy reference",
            ),
        ),
    ]
