# Generated by Django 6.0.2 on 2026-04-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0010_ritualitem_prescription_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="ritualitem",
            name="prescription_image",
            field=models.ImageField(
                blank=True,
                help_text="Photo of the prescription for pharmacy reference",
                null=True,
                upload_to="prescriptions/",
            ),
        ),
    ]
