# Generated by Django 6.0.2 on 2026-04-09 20:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0011_ritualitem_prescription_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Calendar date in user timezone")),
                (
                    "mood",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (5, "great"),
                            (4, "good"),
                            (3, "okay"),
                            (2, "poor"),
                            (1, "bad"),
                        ],
                        help_text="1-5 scale: bad to great",
                        null=True,
                    ),
                ),
                (
                    "energy",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="1-5 scale: exhausted to energized",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "sleep_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Hours of sleep last night",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "sleep_quality",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="1-5 scale: terrible to excellent",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "pain_level",
                    models.SmallIntegerField(
                        default=0,
                        help_text="0-10 pain scale (0 = no pain)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "stress_level",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="1-5 scale: calm to very stressed",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "water_ml",
                    models.PositiveIntegerField(
                        default=0, help_text="Water intake in ml (250ml per glass)"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Free-text daily notes"
                    ),
                ),
                (
                    "wizard_completed",
                    models.BooleanField(
                        default=False,
                        help_text="True when user finished the wizard (even with skips)",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When wizard was completed", null=True
                    ),
                ),
                (
                    "dose_adherence_pct",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Denormalized: % of scheduled doses taken today",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "cached_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Denormalized: {weight, bp_sys, bp_dia, doses_taken, doses_total, ...}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DoseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("taken", models.BooleanField(default=False)),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "skipped_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("forgot", "Forgot"),
                            ("side_effect", "Side Effects"),
                            ("out_of_stock", "Out of Stock"),
                            ("fasting", "Fasting Today"),
                            ("doctor_advised", "Doctor Advised"),
                            ("feeling_unwell", "Feeling Unwell"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MetricTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("weight", "Weight (kg)"),
                            ("body_fat", "Body Fat (%)"),
                            ("bmi", "BMI"),
                            ("bp_systolic", "BP Systolic"),
                            ("bp_diastolic", "BP Diastolic"),
                            ("bp_pulse", "Pulse"),
                            ("mood", "Mood (1-5)"),
                            ("energy", "Energy (1-5)"),
                            ("sleep_hours", "Sleep Hours"),
                            ("sleep_quality", "Sleep Quality (1-5)"),
                            ("water_ml", "Water (ml)"),
                            ("pain", "Pain (0-10)"),
                            ("stress", "Stress (1-5)"),
                            ("dose_adherence", "Dose Adherence (%)"),
                            ("hrv", "HRV (ms)"),
                            ("rhr", "Resting HR"),
                            ("recovery_score", "Recovery Score (%)"),
                            ("strain", "Strain (0-21)"),
                            ("spo2", "SpO2 (%)"),
                            ("health_score", "Health Score (0-100)"),
                            ("uric_acid", "Uric Acid"),
                            ("waist_cm", "Waist (cm)"),
                            ("hip_cm", "Hip (cm)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(blank=True, default="", max_length=20)),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Additional context (e.g., {source: "wizard", bp_stage: "elevated"})',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "metric_type"],
            },
        ),
        migrations.CreateModel(
            name="Supplement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Product name (e.g., "Vitamin D3 2000IU")',
                        max_length=200,
                    ),
                ),
                (
                    "name_bg",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bulgarian name",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("supplement", "Supplement"),
                            ("vitamin", "Vitamin"),
                            ("mineral", "Mineral"),
                            ("medication", "Prescription Medication"),
                            ("otc", "Over-the-Counter Drug"),
                            ("injection", "Injection"),
                            ("herb", "Herbal/Natural"),
                            ("probiotic", "Probiotic"),
                            ("protein", "Protein/Amino Acid"),
                            ("other", "Other"),
                        ],
                        default="supplement",
                        max_length=20,
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("softgel", "Softgel"),
                            ("liquid", "Liquid"),
                            ("powder", "Powder"),
                            ("drops", "Drops"),
                            ("injection", "Injection"),
                            ("patch", "Patch"),
                            ("spray", "Spray"),
                            ("gummy", "Gummy"),
                            ("lozenge", "Lozenge"),
                            ("other", "Other"),
                        ],
                        default="tablet",
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Pill color (e.g., "white", "yellow", "brown")',
                        max_length=50,
                    ),
                ),
                (
                    "shape",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Pill shape (e.g., "round", "oval", "oblong")',
                        max_length=50,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Approximate size (e.g., "small", "large")',
                        max_length=50,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Package photo for identification",
                        null=True,
                        upload_to="health/supplements/package/",
                    ),
                ),
                (
                    "photo_closeup",
                    models.ImageField(
                        blank=True,
                        help_text="Close-up pill photo with scale reference",
                        null=True,
                        upload_to="health/supplements/closeup/",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "strength",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Per-unit strength (e.g., "2000IU", "500mg", "10ml")',
                        max_length=50,
                    ),
                ),
                (
                    "strength_unit",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Unit of strength (mg, IU, mcg, ml, g)",
                        max_length=20,
                    ),
                ),
                ("barcode", models.CharField(blank=True, default="", max_length=50)),
                (
                    "pack_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of units in one package",
                        null=True,
                    ),
                ),
                (
                    "current_stock",
                    models.PositiveIntegerField(
                        default=0, help_text="Current units remaining"
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Alert when stock drops below this many days of supply",
                    ),
                ),
                ("is_prescription", models.BooleanField(default=False)),
                (
                    "prescribing_doctor",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("prescription_note", models.TextField(blank=True, default="")),
                (
                    "linked_biomarkers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of biomarker slugs this supplement targets (e.g., ["vitamin_d", "calcium"])',
                    ),
                ),
                (
                    "interactions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Known interactions: [{"with": "iron", "type": "absorption", "note": "Take 2h apart"}]',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "started_at",
                    models.DateField(
                        blank=True,
                        help_text="When user started taking this (for before/after analysis)",
                        null=True,
                    ),
                ),
                ("discontinued_at", models.DateField(blank=True, null=True)),
                (
                    "discontinue_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupplementSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("morning", "Morning (wake up)"),
                            ("fasted", "Fasted (before food)"),
                            ("breakfast", "With Breakfast"),
                            ("midday", "Midday"),
                            ("lunch", "With Lunch"),
                            ("afternoon", "Afternoon"),
                            ("dinner", "With Dinner"),
                            ("evening", "Evening"),
                            ("bedtime", "Bedtime"),
                        ],
                        default="morning",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_time",
                    models.TimeField(
                        blank=True,
                        help_text="Preferred time (for notifications). Null = use time_slot default.",
                        null=True,
                    ),
                ),
                (
                    "dose_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Number of units per dose (e.g., 1, 0.5 for half pill, 2 for two pills)",
                        max_digits=5,
                    ),
                ),
                (
                    "dose_unit",
                    models.CharField(
                        choices=[
                            ("pill", "Pill(s)"),
                            ("capsule", "Capsule(s)"),
                            ("ml", "ml"),
                            ("drops", "Drop(s)"),
                            ("scoop", "Scoop(s)"),
                            ("spray", "Spray(s)"),
                            ("patch", "Patch"),
                            ("injection", "Injection"),
                        ],
                        default="pill",
                        max_length=20,
                    ),
                ),
                (
                    "split_count",
                    models.SmallIntegerField(
                        default=1,
                        help_text="How many pieces the unit is split into (1=whole, 2=half, 4=quarter)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "take_with_food",
                    models.BooleanField(
                        default=False, help_text="Must be taken with food"
                    ),
                ),
                (
                    "take_with_water",
                    models.BooleanField(default=True, help_text="Take with water"),
                ),
                (
                    "take_on_empty_stomach",
                    models.BooleanField(
                        default=False, help_text="Must be taken fasted"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("daily", "Every Day"),
                            ("gym_day", "Gym Days Only"),
                            ("as_needed", "As Needed"),
                            ("alternate", "Every Other Day"),
                            ("weekdays", "Weekdays Only"),
                            ("custom", "Custom Days"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "days_of_week",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="For custom condition: [0,1,2,3,4] = Mon-Fri. Empty = every day.",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sort_order",
                    models.SmallIntegerField(
                        default=0, help_text="Order within time slot"
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["time_slot", "sort_order", "supplement__name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="bodymeasurement",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="bodymeasurement",
            name="health_body_user_id_1178de_idx",
        ),
        migrations.RemoveIndex(
            model_name="ritualitem",
            name="health_ritu_user_id_2df1fa_idx",
        ),
        migrations.AlterUniqueTogether(
            name="rituallog",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="rituallog",
            name="health_ritu_date_8f6c9e_idx",
        ),
        migrations.AlterField(
            model_name="weightreading",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("csv", "CSV Import"),
                    ("wizard", "Daily Wizard"),
                    ("withings", "Withings"),
                    ("apple_health", "Apple Health"),
                    ("garmin", "Garmin"),
                    ("renpho", "Renpho"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_logs",
                to="health.healthprofile",
            ),
        ),
        migrations.AddField(
            model_name="dailylog",
            name="user",
            field=models.ForeignKey(
                help_text="Redundant with profile.user — denormalized for query speed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="metrictimeline",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metric_timeline",
                to="health.healthprofile",
            ),
        ),
        migrations.AddField(
            model_name="metrictimeline",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metric_timeline",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supplement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supplementschedule",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplement_schedules",
                to="health.healthprofile",
            ),
        ),
        migrations.AddField(
            model_name="supplementschedule",
            name="supplement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="health.supplement",
            ),
        ),
        migrations.AddField(
            model_name="doselog",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dose_logs",
                to="health.supplementschedule",
            ),
        ),
        migrations.RemoveField(
            model_name="bodymeasurement",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="bodymeasurement",
            name="user",
        ),
        migrations.RemoveField(
            model_name="ritualitem",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="ritualitem",
            name="user",
        ),
        migrations.RemoveField(
            model_name="rituallog",
            name="item",
        ),
        migrations.AddIndex(
            model_name="dailylog",
            index=models.Index(
                fields=["user", "profile", "-date"],
                name="health_dail_user_id_338c93_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dailylog",
            index=models.Index(
                fields=["user", "-date"], name="health_dail_user_id_e81f35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailylog",
            index=models.Index(
                fields=["profile", "-date"], name="health_dail_profile_3e436f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailylog",
            unique_together={("profile", "date")},
        ),
        migrations.AddIndex(
            model_name="metrictimeline",
            index=models.Index(
                fields=["user", "profile", "-date"],
                name="health_metr_user_id_515dcd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metrictimeline",
            index=models.Index(
                fields=["user", "-date", "metric_type"],
                name="health_metr_user_id_47e881_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metrictimeline",
            index=models.Index(
                fields=["profile", "metric_type", "-date"],
                name="health_metr_profile_711b5a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="metrictimeline",
            unique_together={("profile", "date", "metric_type")},
        ),
        migrations.AddIndex(
            model_name="supplement",
            index=models.Index(
                fields=["user", "is_active"], name="health_supp_user_id_1f5d20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplement",
            index=models.Index(
                fields=["user", "category"], name="health_supp_user_id_c1132d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplementschedule",
            index=models.Index(
                fields=["profile", "is_active"], name="health_supp_profile_9a2882_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplementschedule",
            index=models.Index(
                fields=["supplement", "is_active"],
                name="health_supp_supplem_fe7c31_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="doselog",
            index=models.Index(
                fields=["date", "taken"], name="health_dose_date_d86525_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doselog",
            index=models.Index(
                fields=["schedule", "-date"], name="health_dose_schedul_5c5e2c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="doselog",
            unique_together={("schedule", "date")},
        ),
        migrations.DeleteModel(
            name="BodyMeasurement",
        ),
        migrations.DeleteModel(
            name="RitualItem",
        ),
        migrations.DeleteModel(
            name="RitualLog",
        ),
    ]
