# Generated by Django 6.0.2 on 2026-04-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0012_add_daily_log_supplement_schedule_doselog_timeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplement",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price paid for one pack (matching pack_size)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supplement",
            name="currency",
            field=models.CharField(
                default="EUR",
                help_text="ISO 4217 currency code (EUR, BGN, USD, ...)",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="supplement",
            name="purchase_date",
            field=models.DateField(
                blank=True, help_text="Date of last purchase", null=True
            ),
        ),
    ]
