# Generated by Django 6.0.2 on 2026-04-10 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0013_supplement_cost_supplement_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Drugs, foods, environmental — anything that could trigger anaphylaxis.",
                    ),
                ),
                (
                    "chronic_conditions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Diabetes, epilepsy, heart disease, etc.",
                    ),
                ),
                (
                    "current_medications_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Manual override. If empty, the frontend lists active Supplement items with category=medication.",
                    ),
                ),
                ("recent_surgeries", models.TextField(blank=True, default="")),
                (
                    "implants",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Pacemaker, stents, prosthetics, metal screws (relevant for MRI).",
                    ),
                ),
                ("organ_donor", models.BooleanField(default=False)),
                (
                    "dnr",
                    models.BooleanField(default=False, help_text="Do Not Resuscitate"),
                ),
                ("advance_directive_url", models.URLField(blank=True, default="")),
                (
                    "insurance_provider",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "insurance_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "emergency_contacts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="In Case of Emergency contacts.",
                    ),
                ),
                (
                    "primary_doctor_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "primary_doctor_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_card",
                        to="health.healthprofile",
                    ),
                ),
            ],
        ),
    ]
