# Generated by Django 6.0.2 on 2026-04-10 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0014_emergencycard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seen",
                    models.BooleanField(
                        default=False,
                        help_text="True after the toast was shown to the user.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-unlocked_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-unlocked_at"],
                        name="health_achi_user_id_b76e7a_idx",
                    )
                ],
                "unique_together": {("user", "code")},
            },
        ),
    ]
