# Generated by Django 6.0.2 on 2026-04-10 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0015_achievement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FastingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("16_8", "16:8 (Leangains)"),
                            ("18_6", "18:6"),
                            ("20_4", "20:4 (Warrior)"),
                            ("omad", "OMAD (23:1)"),
                            ("24h", "24-hour fast"),
                            ("36h", "36-hour fast"),
                            ("48h", "48-hour fast"),
                            ("custom", "Custom window"),
                        ],
                        default="16_8",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Planned break-fast time. Null = open-ended.",
                        null=True,
                    ),
                ),
                (
                    "ended_early_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set if user broke fast before ends_at.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fasting_sessions",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fasting_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "profile", "-starts_at"],
                        name="health_fast_user_id_576a38_idx",
                    )
                ],
            },
        ),
    ]
