# Generated by Django 6.0.2 on 2026-04-10 10:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0016_fastingsession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("headache", "Headache"),
                            ("migraine", "Migraine"),
                            ("fatigue", "Fatigue"),
                            ("nausea", "Nausea"),
                            ("dizziness", "Dizziness"),
                            ("insomnia", "Insomnia / Poor Sleep"),
                            ("joint_pain", "Joint Pain"),
                            ("muscle_pain", "Muscle Pain"),
                            ("back_pain", "Back Pain"),
                            ("digestive", "Digestive Upset"),
                            ("bloating", "Bloating"),
                            ("skin", "Skin Reaction"),
                            ("allergy", "Allergy Symptoms"),
                            ("mood_low", "Low Mood"),
                            ("anxiety", "Anxiety"),
                            ("heart_palpitations", "Heart Palpitations"),
                            ("shortness_of_breath", "Shortness of Breath"),
                            ("brain_fog", "Brain Fog"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.SmallIntegerField(
                        help_text="1-10 scale, 10 = worst imaginable",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        help_text="When the symptom started (defaults to now on create)."
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total duration if known.", null=True
                    ),
                ),
                (
                    "body_location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Free-text body location (e.g., "right temple", "lower back").',
                        max_length=200,
                    ),
                ),
                (
                    "triggers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='User-suspected triggers: ["skipped lunch", "stress", "iron pill"]',
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptoms",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptoms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "profile", "-occurred_at"],
                        name="health_symp_user_id_4218e4_idx",
                    ),
                    models.Index(
                        fields=["user", "category", "-occurred_at"],
                        name="health_symp_user_id_f03b0f_idx",
                    ),
                ],
            },
        ),
    ]
