# Generated by Django 6.0.2 on 2026-04-10 11:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0017_symptom"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='City or coordinates (e.g., "Sofia, Bulgaria" or "42.7°N, 23.3°E")',
                        max_length=200,
                    ),
                ),
                (
                    "temperature_celsius",
                    models.FloatField(
                        blank=True, help_text="Mean temperature in °C", null=True
                    ),
                ),
                (
                    "temp_min",
                    models.FloatField(
                        blank=True, help_text="Minimum temperature in °C", null=True
                    ),
                ),
                (
                    "temp_max",
                    models.FloatField(
                        blank=True, help_text="Maximum temperature in °C", null=True
                    ),
                ),
                (
                    "humidity_percent",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Relative humidity 0-100%",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "pressure_hpa",
                    models.FloatField(
                        blank=True, help_text="Atmospheric pressure in hPa", null=True
                    ),
                ),
                (
                    "wind_speed_kmh",
                    models.FloatField(
                        blank=True, help_text="Wind speed in km/h", null=True
                    ),
                ),
                (
                    "precipitation_mm",
                    models.FloatField(
                        blank=True,
                        default=0,
                        help_text="Daily precipitation in mm (rain + snow water equivalent)",
                        null=True,
                    ),
                ),
                (
                    "air_quality_index",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="AQI 0-500+ (0=best, 300+=hazardous). None if not available.",
                        null=True,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("clear", "Clear"),
                            ("cloudy", "Cloudy"),
                            ("rainy", "Rainy"),
                            ("snowy", "Snowy"),
                            ("stormy", "Stormy"),
                            ("fog", "Fog"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        help_text="Summary of conditions",
                        max_length=20,
                    ),
                ),
                (
                    "condition_detail",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Additional detail (e.g., "light rain", "scattered clouds")',
                        max_length=200,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("openweathermap", "OpenWeatherMap"),
                            ("manual", "Manual Entry"),
                            ("imported", "Imported"),
                        ],
                        default="openweathermap",
                        max_length=20,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw JSON response from API (for future feature enhancement)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_snapshots",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="health_weat_user_id_7c78de_idx"
                    ),
                    models.Index(
                        fields=["profile", "-date"],
                        name="health_weat_profile_99f012_idx",
                    ),
                ],
                "unique_together": {("profile", "date")},
            },
        ),
    ]
