# Generated by Django 6.0.2 on 2026-04-10 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0018_weathersnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaregiverRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of allowed actions: ["view_all", "log_doses", "edit_schedules", "edit_supplements"]',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Acceptance"),
                            ("accepted", "Accepted"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "relationship_note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g., "My spouse", "My child", "My nurse"',
                        max_length=200,
                    ),
                ),
                (
                    "caregiver_user",
                    models.ForeignKey(
                        help_text="The caregiver (e.g., adult child, spouse, healthcare provider)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caregiver_relationships_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        help_text="Which profile the caregiver has access to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caregiver_relationships",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The owner granting access (e.g., parent)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caregiver_relationships_primary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="health_care_user_id_a9a3ec_idx"
                    ),
                    models.Index(
                        fields=["caregiver_user", "status"],
                        name="health_care_caregiv_a2d258_idx",
                    ),
                    models.Index(
                        fields=["profile", "status"],
                        name="health_care_profile_c0530a_idx",
                    ),
                ],
                "unique_together": {("user", "profile", "caregiver_user")},
            },
        ),
    ]
