# Generated by Django 6.0.2 on 2026-04-10 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0019_caregiverrelationship"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medication_name",
                    models.CharField(
                        help_text='Name of medication (e.g., "Lisinopril 10mg", "Vitamin D 2000IU")',
                        max_length=200,
                    ),
                ),
                (
                    "reminder_time",
                    models.TimeField(
                        help_text="Time of day to be reminded (e.g., 08:00)"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "Once"),
                            ("daily", "Every day"),
                            ("weekdays", "Weekdays only"),
                            ("weekends", "Weekends only"),
                            ("custom", "Custom days"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "custom_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Days of week if frequency=custom: [0=Mon, 1=Tue, ..., 6=Sun]",
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="When reminder stops (null = ongoing)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "last_taken_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user last confirmed taking this medication",
                        null=True,
                    ),
                ),
                (
                    "skipped_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of missed reminders"
                    ),
                ),
                (
                    "taken_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of confirmed taken"
                    ),
                ),
                (
                    "dosage",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g., "1 tablet", "5ml", "1 capsule"',
                        max_length=200,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text='e.g., "With food", "Before bed", "On empty stomach"',
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_reminders",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "supplement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to supplement (optional, for context)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="health.supplement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["reminder_time", "medication_name"],
            },
        ),
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("taken", "Taken"),
                            ("snoozed", "Snoozed"),
                            ("skipped", "Skipped"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "snoozed_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="When snoozed reminder should fire again",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="health.medicationreminder",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="medicationreminder",
            index=models.Index(
                fields=["user", "status", "-updated_at"],
                name="health_medi_user_id_432561_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicationreminder",
            index=models.Index(
                fields=["profile", "status"], name="health_medi_profile_9f62eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicationreminder",
            index=models.Index(
                fields=["user", "reminder_time"], name="health_medi_user_id_dafff3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reminderlog",
            index=models.Index(
                fields=["reminder", "date"], name="health_remi_reminde_1c479a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reminderlog",
            index=models.Index(
                fields=["status", "date"], name="health_remi_status_8812a9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reminderlog",
            unique_together={("reminder", "date")},
        ),
    ]
