# Generated by Django 6.0.2 on 2026-04-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0020_medicationreminder_reminderlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bpmedication",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo of pill/package for visual identification",
                null=True,
                upload_to="health/bp_medications/pill/",
            ),
        ),
        migrations.AddField(
            model_name="bpmedication",
            name="photo_prescription",
            field=models.ImageField(
                blank=True,
                help_text="Photo of prescription/doctor document",
                null=True,
                upload_to="health/bp_medications/prescription/",
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo of pill/package for visual identification",
                null=True,
                upload_to="health/interventions/pill/",
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="photo_prescription",
            field=models.ImageField(
                blank=True,
                help_text="Photo of prescription/doctor document",
                null=True,
                upload_to="health/interventions/prescription/",
            ),
        ),
    ]
