# Generated by Django 6.0.2 on 2026-04-12 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0022_protocol_engine"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealTiming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_slot", models.CharField(max_length=5)),
                ("meal_name", models.CharField(max_length=100)),
                (
                    "meal_name_bg",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("description_bg", models.TextField(blank=True, default="")),
                (
                    "nutritional_focus",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "supplement_ids",
                    models.JSONField(blank=True, default=list),
                ),
                ("water_ml", models.IntegerField(blank=True, null=True)),
                (
                    "suggested_foods",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "suggested_foods_bg",
                    models.JSONField(blank=True, default=list),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("notes_bg", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meal_timings",
                        to="health.healthprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_timings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["time_slot"],
            },
        ),
        migrations.AddIndex(
            model_name="mealtiming",
            index=models.Index(
                fields=["user", "time_slot"], name="health_meal_user_id_124c53_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mealtiming",
            unique_together={("user", "profile", "time_slot")},
        ),
    ]
