# Generated by Django 6.0.2 on 2026-04-01 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListeningHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("played_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-played_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="song",
            new_name="music_song_user_id_280aa7_idx",
            old_name="music_song_user_id_abc123_idx",
        ),
        migrations.AddField(
            model_name="song",
            name="color_hex",
            field=models.CharField(default="#6366f1", max_length=7),
        ),
        migrations.AddField(
            model_name="song",
            name="is_favorite",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="song",
            name="last_played_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="song",
            name="play_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["user", "is_favorite"], name="music_song_user_id_5b31be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["user", "-play_count"], name="music_song_user_id_109b85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["user", "-last_played_at"], name="music_song_user_id_31a013_idx"
            ),
        ),
        migrations.AddField(
            model_name="listeninghistory",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_entries",
                to="music.song",
            ),
        ),
        migrations.AddField(
            model_name="listeninghistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listening_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="listeninghistory",
            index=models.Index(
                fields=["user", "-played_at"], name="music_liste_user_id_9e039b_idx"
            ),
        ),
    ]
